import {WEAPONS} from './weapons.ts';
const HERO_DEFINITIONS = [
  { id:'shevchenko', name:'Тарас Шевченко', weapon:'Булава слова', special:'Заповіт', ultimate:'Воля', specialCooldown:8, specialCharges:1, description:'Булава — звукові хвилі, що позначають ворогів для ланцюгової блискавки. «Заповіт»: піхота поруч у паніці тікає з криком протягом 3 с. Ульта «Воля»: небесне перо викликає блискавки попереду.', speed:7, sheet:'/assets/shevchenko-mace-sheet.png', color:'#ffd16b' },
  { id:'lesya', name:'Леся Українка', weapon:'Отруйний арбалет', special:'Зграя ворон', ultimate:'Бойова Мавка', specialCooldown:9, specialCharges:1, description:'Арбалет — стріли з отрутою на 3 с. Ворони переслідують отруєну ціль, ранять її й поширюють отруту. Без мітки відволікають ворогів. Ульта: Мавка на 6 с — рухоме коріння хапає ворогів.', speed:7.6, sheet:'/assets/lesya-crossbow-sheet.png', color:'#6de8bd' },
  { id:'franko', name:'Іван Франко', weapon:'Молот каменяра', special:'Кам’яний заслін', ultimate:'Лупайте сю скалу!', specialCooldown:10, specialCharges:2, description:'Молот — важкий удар зблизька. Кам’яний заслін на 4 с перехоплює ворожі кулі й утворює сходинку для стрибка. Два заряди, кожен відновлюється 10 с. Ульта — ударна хвиля, що розбиває укриття з обох боків.', speed:6.8, sheet:'/assets/franko-coarse-sheet.png', color:'#e2bd91' },
  {"id": "bandera", "name": "Степан Бандера", "weapon": "ППШ", "special": "Бандерівський смузі", "ultimate": "Бандермобіль", "specialCooldown": 7, "specialCharges": 2, "description": "ППШ — швидка черга. Два коктейлі залишають вогонь на землі. Бандермобіль таранить ворогів; повторне натискання ульти підриває його достроково.", "speed": 7.2, "sheet": "/assets/bandera-pixel-sheet.png", "color": "#f9aa69"},
  {"id": "mamai", "name": "Козак Мамай", "weapon": "Шабля та кремінний пістоль", "special": "Бандура-бумеранг", "ultimate": "Примарна кіннота", "specialCooldown": 6, "specialCharges": 2, "description": "Коротке натискання — шабля при відпусканні. Утримання 0,3 с — постріл із пістоля. Бандура ранить на шляху туди й назад. Примарні козаки проривають укриття.", "speed": 7.3, "sheet": "/assets/mamai-pixel-sheet.png", "color": "#efc572"},
  {"id": "bayraktar", "name": "Байрактарчик", "weapon": "Наплічна турель", "special": "Дрон-камікадзе", "ultimate": "Ракетний рій", "specialCooldown": 8, "specialCharges": 2, "description": "Турель стріляє швидкою чергою. Два заряди дронів: шукають цілі в межах 16 м і розподіляють їх між собою. Без цілі супроводжують бійця до 6 с. Ракетний рій накриває позначені ділянки попереду.", "speed": 7.1, "sheet": "/assets/bayraktar-pixel-sheet.png", "color": "#f4d769"},
  {"id": "ghost", "name": "Привид Києва", "weapon": "Бортовий автомат", "special": "Невидимий маневр", "ultimate": "Авіаналіт", "specialCooldown": 9, "specialCharges": 1, "description": "Автомат — швидкі далекі постріли. Маневр на 3 с приховує бійця та прискорює рух; вогонь знімає маскування. Винищувач скидає бомби вздовж маршруту.", "speed": 7.8, "sheet": "/assets/ghost-pixel-sheet.png", "color": "#8fe1f6"},
  {"id": "zelensky", "name": "Володимир Зеленський", "weapon": "Глок і мікрофон", "special": "Підкріплення", "ultimate": "Прапорний дрон", "specialCooldown": 12, "specialCharges": 1, "description": "Кожен третій постріл супроводжується хвилею голосу, що змушує піхоту зблизька тікати з криком на 1,25 с. Двоє піхотинців із 60 ОЗ супроводжують героя, шукають ворогів і стріляють чергами з перезаряджанням. Повторний виклик поповнює втрати; для повного загону перемикає утримання позиції. Великий дрон із прапором атакує попереду.", "speed": 7.2, "sheet": "/assets/zelensky-pixel-sheet.png", "color": "#bce07b"},
  {"id": "bilozerska", "name": "Олена Білозерська", "weapon": "Снайперська гвинтівка", "special": "Міни", "ultimate": "Наскрізний постріл", "specialCooldown": 6, "specialCharges": 3, "description": "Гвинтівка вражає одну ціль. Стій нерухомо 0,8 с для посиленого прицільного пострілу. Три міни спрацьовують від ворогів після короткого взведення. Ульта після прицілювання прошиває ворогів і стіни.", "speed": 6.9, "sheet": "/assets/bilozerska-pixel-sheet.png", "color": "#e4d1ab"},
  {"id": "it-army", "name": "IT-Армія UA", "weapon": "ЕМІ-імпульс", "special": "Перехоплення танка", "ultimate": "DDoS", "specialCooldown": 10, "specialCharges": 2, "description": "ЕМІ коротко паралізує ціль. Танк у межах 14 м переходить на наш бік на 8 с. Без танка з’являється власний робот зі 110 ОЗ. Ліміт перехоплення та робота окремий для кожного гравця. DDoS зупиняє ворогів у широкій зоні на 5 с.", "speed": 7.4, "sheet": "/assets/it-army-pixel-sheet.png", "color": "#88f3da"},
  {"id": "skovoroda", "name": "Григорій Сковорода", "weapon": "Пательня", "special": "Летючий трактат", "ultimate": "Світ не впіймав", "specialCooldown": 8, "specialCharges": 2, "description": "Пательня б’є зблизька й відбиває кулі. Трактат повертається та вражає двічі. Поле спокою 5 с відбиває кулі, стримує ворогів і відновлює здоров’я.", "speed": 7.4, "sheet": "/assets/skovoroda-pixel-sheet.png", "color": "#c0c9f9"},
  {"id": "usyk", "name": "Олександр Усик", "weapon": "Швидка трійка", "special": "Крок убік", "ultimate": "Чемпіонська серія", "specialCooldown": 5, "specialCharges": 2, "description": "Три удари: джеб, крос, аперкот. Маневр скорочує дистанцію та захищає від куль. Ульта прискорює серію на 5 с.", "speed": 8.4, "sheet": "/assets/usyk-pixel-sheet.png", "color": "#ffe078"},
  {"id": "almaziv", "name": "Олекса Алмазів", "weapon": "Кишенькова гармата", "special": "Картеч", "ultimate": "Батарея, вогонь!", "specialCooldown": 8, "specialCharges": 2, "description": "Гранати летять дугою та відскакують один раз. Картеч відкидає ближніх ворогів. Батарея запускає три важкі снаряди з тієї самої позиції.", "speed": 6.8, "sheet": "/assets/almaziv-pixel-sheet.png", "color": "#c28f52"},
  {"id": "klychko", "name": "Віталій Кличко", "weapon": "Важка двійка", "special": "Залізний блок", "ultimate": "Час чемпіона", "specialCooldown": 7, "specialCharges": 2, "description": "Важкі удари відкидають ворогів. Блок спереду перехоплює кулю та відповідає контрударом. Ульта на 5 с сповільнює ворогів і їхні снаряди.", "speed": 6.7, "sheet": "/assets/klychko-pixel-sheet.png", "color": "#dc5835"},
  {"id": "taira", "name": "Юлія «Тайра» Паєвська", "weapon": "З дороги", "special": "Тримайся", "ultimate": "Своїх не лишаємо", "specialCooldown": 14, "specialCharges": 2, "description": "Ближній удар звільняє шлях. Медпакет відновлює 25 ОЗ пораненому союзнику або собі. Ульта рятує одного павшого напарника у хвилях або лікує й захищає загін.", "speed": 7.8, "sheet": "/assets/taira-pixel-sheet.png", "color": "#79dbc0"},
  {"id": "prytula", "name": "Сергій Притула", "weapon": "Експрес-доставка", "special": "Посилка прибула", "ultimate": "Народна броня", "specialCooldown": 12, "specialCharges": 1, "description": "Карабін стріляє трійками. Робот супроводжує бійця та поповнює магазин. Ульта доставляє танк із 200 броні й вісьмома снарядами; сісти може будь-хто.", "speed": 7.2, "sheet": "/assets/prytula-pixel-sheet.png", "color": "#96a657"},
] as const;
export type HeroId=typeof HERO_DEFINITIONS[number]['id'];
export const HEROES=HERO_DEFINITIONS.map(h=>({...h,...WEAPONS[h.id],projectileLife:WEAPONS[h.id].range/WEAPONS[h.id].projectileSpeed}));
export const ACTIVE_HEROES=HEROES.filter(h=>!(['ghost','skovoroda'] as string[]).includes(h.id));
export const heroById=(id:string)=>HEROES.find(h=>h.id===id)??HEROES[0];
export {MISSIONS,type Mission} from './missions.ts';
