import {WEAPONS} from './weapons.ts';
const HERO_DEFINITIONS = [
  { id:'shevchenko', name:'Тарас Шевченко', weapon:'Булава слова', special:'Заповіт', ultimate:'Воля', specialCooldown:8, specialCharges:1, description:'Булава — звукові хвилі. «Заповіт»: піхота поруч у паніці тікає з криком протягом 3 с. Ульта «Воля»: небесне перо викликає блискавки попереду.', speed:7, sheet:'/assets/shevchenko-mace-sheet.png', color:'#ffd16b' },
  { id:'lesya', name:'Леся Українка', weapon:'Отруйний арбалет', special:'Зграя ворон', ultimate:'Бойова Мавка', specialCooldown:9, specialCharges:1, description:'Арбалет — стріли з отрутою на 3 с. Ворони на 4 с змушують піхоту з криком тікати; техніку відволікають. Ульта: Мавка на 6 с — рухоме коріння хапає ворогів.', speed:7.6, sheet:'/assets/lesya-crossbow-sheet.png', color:'#6de8bd' },
  { id:'franko', name:'Іван Франко', weapon:'Молот каменяра', special:'Кам’яний заслін', ultimate:'Лупайте сю скалу!', specialCooldown:10, specialCharges:2, description:'Молот — важкий удар зблизька. Кам’яний заслін на 4 с перехоплює ворожі кулі. Два заряди, кожен відновлюється 10 с. Ульта — ударна хвиля, що розбиває укриття з обох боків.', speed:6.8, sheet:'/assets/franko-coarse-sheet.png', color:'#e2bd91' },
  {"id": "bandera", "name": "Степан Бандера", "weapon": "ППШ", "special": "Бандерівський смузі", "ultimate": "Бандермобіль", "specialCooldown": 7, "specialCharges": 2, "description": "ППШ — швидка черга. Два коктейлі залишають вогонь на землі. Бандермобіль таранить ворогів і вибухає наприкінці шляху.", "speed": 7.2, "sheet": "/assets/bandera-pixel-sheet.png", "color": "#f9aa69"},
  {"id": "mamai", "name": "Козак Мамай", "weapon": "Шабля та кремінний пістоль", "special": "Бандура-бумеранг", "ultimate": "Примарна кіннота", "specialCooldown": 6, "specialCharges": 2, "description": "Зблизька — шабля, на відстані — пістоль. Бандура ранить на шляху туди й назад. Примарні козаки проривають укриття.", "speed": 7.3, "sheet": "/assets/mamai-pixel-sheet.png", "color": "#efc572"},
  {"id": "bayraktar", "name": "Байрактарчик", "weapon": "Наплічна турель", "special": "Дрон-камікадзе", "ultimate": "Ракетний рій", "specialCooldown": 8, "specialCharges": 2, "description": "Турель стріляє швидкою чергою. Дрон переслідує найближчу ціль. Ракетний рій накриває позначені ділянки попереду.", "speed": 7.1, "sheet": "/assets/bayraktar-pixel-sheet.png", "color": "#f4d769"},
  {"id": "ghost", "name": "Привид Києва", "weapon": "Бортовий автомат", "special": "Невидимий маневр", "ultimate": "Авіаналіт", "specialCooldown": 9, "specialCharges": 1, "description": "Автомат — швидкі далекі постріли. Маневр на 3 с приховує бійця та прискорює рух; вогонь знімає маскування. Винищувач скидає бомби вздовж маршруту.", "speed": 7.8, "sheet": "/assets/ghost-pixel-sheet.png", "color": "#8fe1f6"},
  {"id": "zelensky", "name": "Володимир Зеленський", "weapon": "Глок і мікрофон", "special": "Підкріплення", "ultimate": "Прапорний дрон", "specialCooldown": 12, "specialCharges": 1, "description": "Кожен третій постріл супроводжується хвилею голосу, що змушує піхоту зблизька тікати з криком на 1,25 с. Двоє піхотинців із 60 ОЗ супроводжують героя, шукають ворогів і стріляють чергами з перезаряджанням. Повторний виклик поповнює втрати. Великий дрон із прапором атакує попереду.", "speed": 7.2, "sheet": "/assets/zelensky-pixel-sheet.png", "color": "#bce07b"},
  {"id": "bilozerska", "name": "Олена Білозерська", "weapon": "Снайперська гвинтівка", "special": "Міни", "ultimate": "Наскрізний постріл", "specialCooldown": 6, "specialCharges": 3, "description": "Гвинтівка вражає одну ціль за постріл. Три міни спрацьовують від ворогів після короткого взведення. Ульта після прицілювання прошиває ворогів і стіни.", "speed": 6.9, "sheet": "/assets/bilozerska-pixel-sheet.png", "color": "#e4d1ab"},
  {"id": "it-army", "name": "IT-Армія UA", "weapon": "ЕМІ-імпульс", "special": "Злам радіовузла", "ultimate": "DDoS", "specialCooldown": 10, "specialCharges": 2, "description": "ЕМІ коротко паралізує ціль. Злам радіовузла в межах 14 м викликає одну крокуючу турель зі 110 ОЗ. Вона супроводжує героя й атакує ворогів; без вузла або за живої турелі заряд зберігається. DDoS зупиняє ворогів у широкій зоні на 5 с.", "speed": 7.4, "sheet": "/assets/it-army-pixel-sheet.png", "color": "#88f3da"},
  {"id": "skovoroda", "name": "Григорій Сковорода", "weapon": "Пательня", "special": "Летючий трактат", "ultimate": "Світ не впіймав", "specialCooldown": 8, "specialCharges": 2, "description": "Пательня б’є зблизька й відбиває кулі. Трактат повертається та вражає двічі. Поле спокою 5 с відбиває кулі, стримує ворогів і відновлює здоров’я.", "speed": 7.4, "sheet": "/assets/skovoroda-pixel-sheet.png", "color": "#c0c9f9"},
] as const;
export type HeroId=typeof HERO_DEFINITIONS[number]['id'];
export const HEROES=HERO_DEFINITIONS.map(h=>({...h,...WEAPONS[h.id],projectileLife:WEAPONS[h.id].range/WEAPONS[h.id].projectileSpeed}));
export const heroById=(id:string)=>HEROES.find(h=>h.id===id)??HEROES[0];
export {MISSIONS,type Mission} from './missions.ts';
