// English UI catalog. Ukrainian source phrases remain stable simulation data.
export const EN:Record<string,string>={
  "Рух і драбини":"Movement and ladders",
  "Не завантажилися ефекти:": "Effects failed to load:",
  "Тарас Шевченко": "Taras Shevchenko",
  "Леся Українка": "Lesya Ukrainka",
  "Іван Франко": "Ivan Franko",
  "Степан Бандера": "Stepan Bandera",
  "Бандер-Бро": "Bander-Bro",
  "Козак Мамай": "Cossack Mamai",
  "Байрактарчик": "Bayraktarchyk",
  "Привид Києва": "Ghost of Kyiv",
  "Володимир Зеленський": "Volodymyr Zelenskyy",
  "Олена Білозерська": "Olena Bilozerska",
  "Айті-армія": "IT Army",
  "Григорій Сковорода": "Hryhorii Skovoroda",
  "Хуйло": "Khuylo",
  "Кремлівський агресор · фінальний бій": "Kremlin aggressor · final battle",
  "Ціль — Хуйло": "Target: Khuylo",
  "Хуйло переможено": "Khuylo defeated",
  "РАКЕТНИЙ ЗАЛП": "MISSILE SALVO",
  "ВИКЛИК ДРОНІВ": "DRONE CALL",
  "ОБСТРІЛ": "BARRAGE",
  "Валерій Герасімов": "Valery Gerasimov",
  "Російський генерал · броньований штаб": "Russian general · armored headquarters",
  "Здолайте Герасімова": "Defeat Gerasimov",
  "Герасімова переможено": "Gerasimov defeated",
  "ГАРМАТНИЙ ЗАЛП": "CANNON SALVO",
  "ТАРАН": "RAM",
  "Сергій Суровікін": "Sergey Surovikin",
  "Російський генерал · повітряний удар": "Russian general · air strike",
  "Здолайте Суровікіна": "Defeat Surovikin",
  "Суровікіна переможено": "Surovikin defeated",
  "ВОГНЕВИЙ ВАЛ": "ROLLING BARRAGE",
  "ГОЛОВНИЙ ВОРОГ": "THE MAIN ENEMY",
  "РОСІЙСЬКЕ КОМАНДУВАННЯ": "RUSSIAN COMMAND",
  "НОВОГО БІЙЦЯ ВІДКРИТО": "NEW FIGHTER UNLOCKED",
  "Прийняти бій · Enter / ✕ / A": "Face the enemy · Enter / ✕ / A",
  "До бою · Enter / ✕ / A": "Into battle · Enter / ✕ / A",
  "Булава слова": "Mace of Words",
  "Заповіт": "Testament",
  "Воля": "Freedom",
  "Булава — звукові хвилі. «Заповіт»: піхота поруч у паніці тікає з криком протягом 3 с. Ульта «Воля»: небесне перо викликає блискавки попереду.": "The mace fires sound waves. Testament sends nearby infantry fleeing in panic for 3 s. Ultimate — Freedom: a celestial quill calls down lightning ahead.",
  "Отруйний арбалет": "Poison Crossbow",
  "Зграя ворон": "Murder of Crows",
  "Бойова Мавка": "Battle Mavka",
  "Арбалет — стріли з отрутою на 3 с. Ворони на 4 с змушують піхоту з криком тікати; техніку відволікають. Ульта: Мавка на 6 с — рухоме коріння хапає ворогів.": "Crossbow bolts poison for 3 s. Crows send infantry fleeing for 4 s and distract vehicles. Ultimate: a Mavka for 6 s — roaming roots seize enemies.",
  "Молот каменяра": "Stonecutter’s Hammer",
  "Кам’яний заслін": "Stone Barrier",
  "Лупайте сю скалу!": "Break This Rock!",
  "Молот — важкий удар зблизька. Кам’яний заслін на 4 с перехоплює ворожі кулі. Два заряди, кожен відновлюється 10 с. Ульта — ударна хвиля, що розбиває укриття з обох боків.": "The hammer delivers a heavy melee blow. A Stone Barrier intercepts enemy bullets for 4 s. Two charges, each recharging in 10 s. The ultimate sends a shockwave through cover on both sides.",
  "ППШ": "PPSh",
  "Бандерівський смузі": "Bandera Smoothie",
  "Бандермобіль": "Bandermobile",
  "ППШ — швидка черга. Два коктейлі залишають вогонь на землі. Бандермобіль таранить ворогів і вибухає наприкінці шляху.": "The PPSh fires rapid bursts. Two firebombs leave flames on the ground. The Bandermobile rams enemies and explodes at the end of its run.",
  "Шабля та кремінний пістоль": "Saber and Flintlock",
  "Бандура-бумеранг": "Bandura Boomerang",
  "Примарна кіннота": "Phantom Cavalry",
  "Зблизька — шабля, на відстані — пістоль. Бандура ранить на шляху туди й назад. Примарні козаки проривають укриття.": "A saber up close, a pistol at range. The bandura hits on both the outward and return trip. Phantom Cossacks charge through cover.",
  "Наплічна турель": "Shoulder Turret",
  "Дрон-камікадзе": "Kamikaze Drone",
  "Ракетний рій": "Missile Swarm",
  "Турель стріляє швидкою чергою. Дрон переслідує найближчу ціль. Ракетний рій накриває позначені ділянки попереду.": "The turret fires rapid bursts. A drone pursues the nearest target. The missile swarm strikes marked areas ahead.",
  "Бортовий автомат": "Airborne Rifle",
  "Невидимий маневр": "Invisible Maneuver",
  "Авіаналіт": "Air Raid",
  "Автомат — швидкі далекі постріли. Маневр на 3 с приховує бійця та прискорює рух; вогонь знімає маскування. Винищувач скидає бомби вздовж маршруту.": "The rifle fires fast, long-range shots. Maneuver grants stealth and speed for 3 s; firing breaks stealth. A fighter jet drops bombs along its route.",
  "Глок і мікрофон": "Glock and Microphone",
  "Підкріплення": "Reinforcements",
  "Прапорний дрон": "Flag Drone",
  "Кожен третій постріл супроводжується хвилею голосу, що змушує піхоту зблизька тікати з криком на 1,25 с. Двоє піхотинців із 60 ОЗ супроводжують героя, шукають ворогів і стріляють чергами з перезаряджанням. Повторний виклик поповнює втрати. Великий дрон із прапором атакує попереду.": "Every third shot sends a voice wave that makes nearby infantry flee for 1.25 s. Two soldiers with 60 HP follow the hero, find enemies and fire bursts with reloads. Calling again replaces losses. A large flag-bearing drone attacks ahead.",
  "Снайперська гвинтівка": "Sniper Rifle",
  "Міни": "Mines",
  "Наскрізний постріл": "Piercing Shot",
  "Гвинтівка вражає одну ціль за постріл. Три міни спрацьовують від ворогів після короткого взведення. Ульта після прицілювання прошиває ворогів і стіни.": "The rifle hits one target per shot. Three mines detonate near enemies after a short arming delay. The ultimate aims, then pierces enemies and walls.",
  "IT-Армія UA": "IT Army UA",
  "ЕМІ-імпульс": "EMP Pulse",
  "Злам радіовузла": "Radio Hack",
  "ЕМІ коротко паралізує ціль. Злам радіовузла в межах 14 м викликає одну крокуючу турель зі 110 ОЗ. Вона супроводжує героя й атакує ворогів; без вузла або за живої турелі заряд зберігається. DDoS зупиняє ворогів у широкій зоні на 5 с.": "EMP briefly disables a target. Hacking a radio within 14 m calls a walking turret with 110 HP. It follows the hero and attacks enemies; the charge is kept if no radio is nearby or the turret is still alive. DDoS stops enemies in a wide area for 5 s.",
  "Пательня": "Frying Pan",
  "Летючий трактат": "Flying Treatise",
  "Світ не впіймав": "The World Could Not Catch Me",
  "Пательня б’є зблизька й відбиває кулі. Трактат повертається та вражає двічі. Поле спокою 5 с відбиває кулі, стримує ворогів і відновлює здоров’я.": "The pan strikes up close and deflects bullets. The treatise returns, hitting twice. A field of calm deflects bullets, holds back enemies and heals for 5 s.",
  "Танк": "Tank",
  "Ракетоносець": "Missile Carrier",
  "Шахед": "Shahed",
  "Нас тут не було.": "We were never here.",
  "Усе за планом.": "All according to plan.",
  "Це не поразка. Це перегрупування!": "This is not defeat. It’s regrouping!",
  "Стривайте, я взагалі з логістики!": "Wait, I’m just logistics!",
  "Мамо, я думав, це навчальна місія!": "Mom, I thought this was a training mission!",
  "Мені казали, тут самі NPC!": "They said there’d only be NPCs!",
  "Мамо, я в катсцені?": "Mom, am I in a cutscene?",
  "Командире, у мене тут баг!": "Commander, I’ve found a bug!",
  "А можна завантажити сейв?": "Can we load a save?",
  "Я не підписувався на боса!": "I didn’t sign up for a boss fight!",
  "Де кнопка здатися?": "Where’s the surrender button?",
  "Моя смерть не канонічна!": "My death isn’t canon!",
  "Я взагалі декоративний!": "I’m just set dressing!",
  "Втрати? Які втрати?": "Casualties? What casualties?",
  "Це тактичне зникнення.": "A tactical disappearance.",
  "Запишіть: планове вибуття.": "Put me down as scheduled attrition.",
  "У звіті я ще живий!": "I’m still alive in the report!",
  "На це потрібен підпис!": "You need a signature for that!",
  "У мене кінець зміни!": "My shift is over!",
  "Я тільки розписатися!": "I’m only here to sign!",
  "Я за іншим квестом!": "I’m on a different quest!",
  "У мене сюжетна броня!": "I have plot armor!",
  "Я ще не зберігся!": "I haven’t saved yet!",
  "Поставте складність нижче!": "Turn the difficulty down!",
  "Де тут безпечна зона?!": "Where’s the safe zone?!",
  "Мій хітбокс не погоджено!": "My hitbox wasn’t approved!",
  "Мене додадуть у наступному патчі!": "They’ll add me in the next patch!",
  "Респавн входить у контракт?": "Does the contract cover respawns?",
  "Я ще не договорив туторіал!": "I haven’t finished the tutorial!",
  "Мій дублер уже їде!": "My stunt double is on the way!",
  "Мене ще немає в титрах!": "I’m not even in the credits yet!",
  "Це збій відображення перемоги.": "Victory display error.",
  "Доставку не замовляв!": "I didn’t order a delivery!",
  "Бочка не за накладною!": "That barrel isn’t on the invoice!",
  "Повернення тари — куди?": "Where do I return the container?",
  "Мені безконтактну доставку!": "I asked for contactless delivery!",
  "За тару хто розпишеться?": "Who’s signing for this barrel?",
  "Вантаж прийняв. Головою.": "Delivery received. With my head.",
  "Тут мало бути пальне!": "That was supposed to be fuel!",
  "Обережно, крихкий одержувач!": "Handle with care: fragile recipient!",
  "Це святковий салют!": "It’s a celebration firework!",
  "Штаб, я розширюю позицію!": "HQ, I’m expanding my position!",
  "Перегруповуюся по частинах!": "Regrouping in pieces!",
  "Це просто спецефекти!": "It’s just special effects!",
  "Вибух не пройшов погодження!": "That explosion wasn’t approved!",
  "Планове провітрювання!": "Scheduled ventilation!",
  "У звіті напишіть: конфеті.": "Write “confetti” in the report.",
  "Хто замовляв урочистості?": "Who ordered the festivities?",
  "Алло, це техпідтримка?": "Hello, is this tech support?",
  "Штаб, зникаю з мережі!": "HQ, I’m going offline!",
  "Ваш абонент перегруповується.": "The subscriber is currently regrouping.",
  "Перемкніть на живого оператора!": "Put me through to a live operator!",
  "Щит ще на гарантії!": "The shield’s still under warranty!",
  "У сертифікаті інше!": "The certificate says otherwise!",
  "Я ж за укриттям!": "But I’m behind cover!",
  "Це не гарантійний випадок?!": "This isn’t covered by warranty?!",
  "Я дивився в інший приціл!": "I was looking through the other scope!",
  "Мене ж не мало бути видно!": "You weren’t supposed to see me!",
  "Секунду, фокус налаштую!": "One second, let me focus!",
  "У мене камера наближена!": "My camera’s zoomed in!",
  "Перерва на перезарядку!": "Reload break!",
  "У мене ще пів стрічки!": "I’ve still got half a belt!",
  "Кулемет казенний, обережно!": "Careful, that machine gun is government property!",
  "Дайте дочитати інструкцію!": "Let me finish the manual!",
  "Мені обіцяли легкий режим!": "They promised me easy mode!",
  "Я біжу на іншу місію!": "I’m running to another mission!",
  "Моя хоробрість ще вантажиться!": "My courage is still loading!",
  "Штурм перенесено. На завтра.": "Assault postponed. Until tomorrow.",
  "Таймер мав бути довший!": "The timer was supposed to be longer!",
  "Це була репетиція!": "That was a rehearsal!",
  "Де тут скасувати доставку?": "Where do I cancel this delivery?",
  "Я думав, воно на батарейках!": "I thought it ran on batteries!",
  "Операція:": "Operation:",
  "Боєць:": "Fighter:",
  "Стан:": "State:",
  "Сесія:": "Session:",
  "Керування:": "Controls:",
  "Вікно:": "Window:",
  "Браузер:": "Browser:",
  "Повідомити про помилку": "Report a bug",
  "Назад": "Back",
  "Зберегти скриншот гри": "Save game screenshot",
  "Відкрити форму окремо ↗": "Open form separately ↗",
  "Скриншот можна додати до форми нижче. Опис отримає розробник; email необов’язковий.": "You can attach a screenshot to the form below. Your report goes to the developer; email is optional.",
  "Технічні дані, що додаються до звернення": "Technical details attached to the report",
  "Форма повідомлення про помилку UA Force": "UA Force bug report form",
  "Додайте збережений PNG у поле «Скриншоти» нижче. Також можна прикріпити власний знімок.": "Attach the saved PNG in the “Скриншоти” (Screenshots) field below. You can also attach your own screenshot.",
  "Поверни телефон горизонтально. Можна грати й без повного екрана.": "Turn your phone sideways. You can play without fullscreen.",
  "Повноекранний режим недоступний у цьому вікні.": "Fullscreen is unavailable in this window.",
  "Повний екран недоступний. Поверни телефон горизонтально — гра працює у вкладці.": "Fullscreen is unavailable. Turn your phone sideways — the game works in a tab.",
  "Поверни телефон горизонтально; за потреби вимкни блокування обертання.": "Turn your phone sideways; disable rotation lock if needed.",
  "ВОЛЯ": "FREEDOM",
  "Танкова гармата.": "Tank cannon.",
  "Перезаряджання:": "Reloading:",
  "с.": "s.",
  "Готово.": "Ready.",
  "Вийти з танка": "Exit tank",
  "Броня:": "Armor:",
  "Відновлення кожного заряду:": "Recharge per charge:",
  "Загін у повному складі.": "Squad at full strength.",
  "Турель активна.": "Turret active.",
  "Потрібен радіовузол поруч.": "A radio station must be nearby.",
  "Знайдіть ящик боєприпасів.": "Find an ammo crate.",
  "Кнопка": "Button",
  "Мотострілець РФ": "Russian Rifleman",
  "Штурмовик ВДВ": "VDV Assault Trooper",
  "Кулеметник РФ": "Russian Machine Gunner",
  "Снайпер РФ": "Russian Sniper",
  "Розвідник-зв’язківець РФ": "Russian Radio Scout",
  "Щитоносець Росгвардії": "Rosgvardiya Shield Trooper",
  "Підривник-штурмовик РФ": "Russian Explosive Runner",
  "Тихий берег": "Quiet Shore",
  "Херсонщина": "Kherson Region",
  "Пройдіть очеретяний берег, звільніть село й прорвіться до ворожого складу. Бережіть ульту: ящики боєприпасів відновлюють її.": "Cross the reed-lined shore, liberate the village and break through to the enemy depot. Save your ultimate: ammo crates restore it.",
  "Очеретяний берег": "Reed Shore",
  "Звільнене село": "Liberated Village",
  "Склад окупантів": "Occupation Depot",
  "Останній рубіж": "The Last Line",
  "Київ": "Kyiv",
  "Від бульвару через завод до дахів останнього рубежу. Прорвіться до броньованого штабу та здолайте Герасімова.": "From the boulevard through the factory to the rooftops of the last line. Reach the armored headquarters and defeat Gerasimov.",
  "Бульвар": "Boulevard",
  "Промисловий квартал": "Industrial Quarter",
  "Дахи рубежу": "Frontline Rooftops",
  "Острів свободи": "Island of Freedom",
  "Зміїний": "Snake Island",
  "Висадіться на берег, прорвіть пояс бункерів і поверніть порт. У порту здолайте Суровікіна, який керує ракетно-дроновими атаками.": "Land on the shore, breach the bunkers and reclaim the port. Defeat Surovikin, who commands the missile and drone strikes.",
  "Місце висадки": "Landing Site",
  "Пояс бункерів": "Bunker Belt",
  "Військовий порт": "Military Port",
  "Гірський прохід": "Mountain Pass",
  "Карпати": "Carpathians",
  "Підніміться крізь смерекові застави, перетніть підвісні переходи й захопіть станцію канатної дороги. Верхні стежки дають шлях над бронетехнікою.": "Climb through the forest outposts, cross the hanging bridges and capture the cable car station. Upper paths let you bypass armored vehicles.",
  "Смерекова застава": "Fir Outpost",
  "Підвісний перевал": "Hanging Pass",
  "Канатна станція": "Cable Car Station",
  "Сталевий вузол": "Steel Junction",
  "Дніпровщина": "Dnipro Region",
  "Пробийтеся через вокзал та ешелони постачання. Рухайтеся вагонами згори або використайте танк у колійному коридорі. Евакуація — за диспетчерською.": "Fight through the station and supply trains. Travel over the wagons or drive a tank through the railway corridor. Extraction is beyond the signal box.",
  "Покинутий вокзал": "Abandoned Station",
  "Вантажні ешелони": "Freight Trains",
  "Диспетчерський сектор": "Signal Box Sector",
  "Нічна варта": "Night Watch",
  "Полісся": "Polissia",
  "Знайдіть полонених на болотяних заставах і виведіть з ладу радіопост. За радіопостом — командний бункер Хуйла. Здолайте диктатора й зупиніть російський наступ.": "Find the prisoners at the swamp outposts and disable the radio post. Khuylo’s command bunker lies beyond. Defeat the dictator and stop the Russian offensive.",
  "Туманні плавні": "Misty Wetlands",
  "Сторожові вежі": "Watchtowers",
  "Командний бункер Хуйла": "Khuylo’s Command Bunker",
  "Сенсорне керування": "Touch controls",
  "Атака": "Attack",
  "Стрибок": "Jump",
  "Взаємодія": "Interact",
  "Спецприйом": "Special",
  "Ульта": "Ultimate",
  "Поверніть телефон": "Rotate your phone",
  "Поверни телефон": "Rotate your phone",
  "Грати зручніше горизонтально.": "Landscape works best.",
  "Гру призупинено.": "Game paused.",
  "На весь екран": "Fullscreen",
  "До меню": "Main menu",
  "Цей код зайнятий. Створіть кімнату ще раз.": "This code is taken. Try creating a room again.",
  "Кімнату не знайдено. Перевірте код і чи відкрито гру у друга.": "Room not found. Check the code and make sure your friend has the game open.",
  "Не вдалося з’єднатися із сервісом кімнат.": "Could not connect to the room service.",
  "Не вдалося встановити пряме з’єднання. Спробуйте іншу мережу.": "Could not establish a direct connection. Try another network.",
  "Цей браузер не підтримує потрібне з’єднання.": "This browser does not support the required connection.",
  "З’єднання перервано. Створіть нову кімнату.": "Connection interrupted. Create a new room.",
  "Не вдалося встановити зв’язок із другом. Код діагностики:": "Could not connect to your friend. Diagnostic code:",
  ". Оновіть гру в обох і створіть нову кімнату.": ". Both players should refresh the game and create a new room.",
  "Друг не відповідає понад 45 секунд. Перевірте, чи відкрита його вкладка гри.": "Your friend has not responded for over 45 seconds. Check that their game tab is open.",
  "Друг знайдений. Встановлюємо захищене з’єднання…": "Friend found. Establishing a secure connection…",
  "З’єднання з другом:": "Connection to your friend:",
  "Зв’язок встановлено. Узгоджуємо версію гри…": "Connected. Checking game versions…",
  "Кімната вже заповнена. У ній можуть бути двоє.": "This room is full. Only two players can join.",
  "Господар закрив кімнату. Одиночна гра доступна.": "The host closed the room. Single player is still available.",
  "Друг вийшов із кімнати. Створіть нову або грайте самі.": "Your friend left the room. Create another or play solo.",
  "Версії гри різні. Оновіть сторінку в обох браузерах.": "Game versions differ. Both players should refresh the page.",
  "Зв’язок із другом втрачено. Створіть нову кімнату.": "Connection to your friend lost. Create a new room.",
  "Помилка прямого з’єднання. Спробуйте іншу мережу.": "Direct connection error. Try another network.",
  "Ворожий патруль. Не дамо підняти тривогу.": "Enemy patrol. Don’t let them raise the alarm.",
  "Разом. За своїх.": "Together. For our people.",
  "Попереду порт. Знайдемо шлях до полонених.": "The port is ahead. Let’s find a way to the prisoners.",
  "Тримаймося разом. Рушаймо!": "Stay together. Let’s move!",
  "Canvas 2D недоступний": "Canvas 2D unavailable",
  "Не завантажився": "Failed to load",
  "ВРЯТУЙ": "RESCUE",
  "А-А!": "AAH!",
  "НА БОРТ ↓": "BOARD ↓",
  "Дальність": "Range",
  "м. Пауза між ударами": "m. Time between strikes",
  "Черга": "Burst of",
  "пострілів, пауза": "shots, pause",
  "Один постріл на натискання.": "One shot per press.",
  "Магазин:": "Magazine:",
  ". Автоперезаряджання:": ". Auto-reload:",
  "с. Дальність:": "s. Range:",
  "м.": "m.",
  "Кинути бочку": "Throw barrel",
  "Евакуація…": "Extracting…",
  "Звільнити полоненого": "Rescue prisoner",
  "Сісти в танк": "Enter tank",
  "Підняти бочку": "Pick up barrel",
  "Гелікоптер наближається — тримайте точку": "Helicopter inbound — hold the position",
  "Підійдіть до троса біля прапора": "Approach the rope by the flag",
  "До прапора евакуації →": "To the extraction flag →",
  "Поверни телефон горизонтально": "Turn your phone sideways",
  "Пропустити · Enter": "Skip · Enter",
  "кооп /": "co-op /",
  "випробування": "practice",
  "одиночна": "single player",
  "сенсорне керування": "touch controls",
  "клавіатура": "keyboard",
  "КАМПАНІЮ ЗАВЕРШЕНО": "CAMPAIGN COMPLETE",
  "ЕВАКУАЦІЯ УСПІШНА": "EXTRACTION SUCCESSFUL",
  "ЗАГІН ВТРАЧЕНО": "SQUAD LOST",
  "ОПЕРАЦІЮ ПРИЗУПИНЕНО": "OPERATION PAUSED",
  "ЗА СВОЇХ. ДО КІНЦЯ.": "FOR OUR PEOPLE. TO THE END.",
  "Хуйло переможено.": "Khuylo defeated.",
  "Летимо далі.": "On to the next one.",
  "Ще одна спроба.": "One more try.",
  "Тримаємо позицію.": "Holding position.",
  "Командний бункер знищено. Російський наступ зупинено. Усі операції завершено.": "Command bunker destroyed. The Russian offensive has been stopped. All operations complete.",
  "Наступна операція —": "Next operation —",
  "Підкріплення вичерпано. Спробуйте інший маршрут, стрибайте з драбин і використовуйте здібність героя.": "No reinforcements left. Try another route, jump off ladders and use your hero’s abilities.",
  "Гра на паузі. Продовжуйте, коли будете готові.": "Game paused. Continue when you’re ready.",
  "Продовжити": "Resume",
  "Грати знову": "Play again",
  "Наступна операція →": "Next operation →",
  "Спробувати знову": "Try again",
  "Одиночна гра": "Single Player",
  "ВИПРОБУВАННЯ БІЙЦЯ": "FIGHTER PRACTICE",
  "J / RT — зброя · E / RB — спецприйом · Q / LT — ульта. Обери іншого бійця або повтори випробування.": "J / RT — weapon · E / RB — special · Q / LT — ultimate. Pick another fighter or try again.",
  "Повторити випробування": "Repeat practice",
  "Обрати операцію:": "Choose operation:",
  "Ульта відновлюється тільки з ящика боєприпасів.": "Only ammo crates restore your ultimate.",
  "Герой:": "Hero:",
  "· відкрито": "· unlocked",
  "ворогів ·": "enemies ·",
  "звільнено": "rescued",
  "Пауза: вікно втратило фокус": "Paused: window lost focus",
  "Пауза: вкладку приховано": "Paused: tab hidden",
  "Контролер від’єднано. Підключіть його або скористайтеся клавіатурою.": "Controller disconnected. Reconnect it or use your keyboard.",
  "Ліворуч": "Left",
  "Праворуч": "Right",
  "Вогонь": "Fire",
  "Пауза / меню": "Pause / menu",
  "Натисніть нову клавішу. Escape — скасувати.": "Press a new key. Escape to cancel.",
  "Стік / хрестовина": "Stick / D-pad",
  "Відпустіть кнопки геймпада, потім натисніть потрібну. Escape — скасувати.": "Release the gamepad buttons, then press the one you want. Escape to cancel.",
  "Призначення збережено.": "Binding saved.",
  "Призначення скасовано.": "Binding cancelled.",
  "Початок операції": "Operation start",
  "Новий боєць": "New fighter",
  "Контрольна точка": "Checkpoint",
  "Виклик евакуації": "Call extraction",
  "Посадка": "Boarding",
  "Перемога": "Victory",
  "Поразка": "Defeat",
  "Повернення в бій": "Back in action",
  "● Геймпад підключено": "● Gamepad connected",
  "Геймпад: натисніть будь-яку кнопку": "Gamepad: press any button",
  "Відтворюється оголошення…": "Playing announcement…",
  "Готово до прослуховування": "Ready to preview",
  "стандартна розкладка": "standard layout",
  "нестандартна розкладка — перевірте призначення": "non-standard layout — check bindings",
  "кнопок,": "buttons,",
  "осей": "axes",
  "Браузер ще не бачить контролер. Підключіть його та натисніть будь-яку кнопку на активній вкладці.": "The browser cannot see your controller yet. Connect it and press any button while this tab is active.",
  "Автоматично": "Automatic",
  "Вісь": "Axis",
  "Броня танка": "Tank armor",
  "Здоров’я": "Health",
  ". Життя:": ". Lives:",
  "Звільнено полонених:": "Prisoners rescued:",
  "Радіовузол:": "Radio station:",
  "знищено": "destroyed",
  "додаткова ціль": "optional objective",
  "До прапора евакуації": "To the extraction flag",
  "Здолайте командира": "Defeat the commander",
  "кадр/с": "fps",
  "♫ Музика увімкнена": "♫ Music on",
  "♫ Увімкнути музику": "♫ Enable music",
  "Евакуація": "Extraction",
  "Пауза друга": "Friend paused",
  "Підключення…": "Connecting…",
  "Введіть 8 символів коду кімнати.": "Enter the 8-character room code.",
  "Готуємо пряме та резервне з’єднання…": "Preparing direct and fallback connections…",
  "Код:": "Code:",
  "· очікуємо друга": "· waiting for your friend",
  "Друг поруч. Завантаження спільної операції…": "Friend connected. Loading the shared operation…",
  "Резервний сервіс з’єднання недоступний. Спробуйте ще раз за хвилину; одиночна гра працює.": "Fallback connection service unavailable. Try again in a minute; single player still works.",
  "Посилання скопійовано": "Link copied",
  "Скопіюйте посилання з адресного рядка": "Copy the link from the address bar",
  "Найкращий час:": "Best time:",
  "Не вдалося завантажити гру": "Could not load the game",
  "Оновіть сторінку або повідомте про помилку кнопкою внизу.": "Refresh the page or use the bug report button below.",
  "UA Force — безкоштовний український аркадний екшен": "UA Force — free Ukrainian arcade action",
  "Сенсорне керування · тест. Поверни телефон горизонтально та ввімкни повний екран.": "Touch controls · test. Turn your phone sideways and enable fullscreen.",
  "Завантаження…": "Loading…",
  "Заново": "Restart",
  "Удвох онлайн": "Online Co-op",
  "тест": "test",
  "Операції": "Operations",
  "Бійці": "Fighters",
  "До кампанії": "Back to campaign",
  "Налаштування": "Settings",
  "Про гру": "About",
  "Поділитися": "Share",
  "ПАУЗА": "PAUSED",
  "Почати заново": "Restart",
  "Випробувати бійця": "Try a fighter",
  "Головне меню": "Main menu",
  "Запросіть друга. Господар обчислює спільний світ — тримайте його вкладку відкритою.": "Invite a friend. The host simulates the shared world — keep their tab open.",
  "Боєць": "Fighter",
  "Створити кімнату": "Create Room",
  "Код кімнати": "Room code",
  "Приєднатися": "Join Room",
  "Скопіювати запрошення": "Copy invitation",
  "Ранній тест для двох. У деяких мережах пряме з’єднання може не працювати. Без перенесення господаря; після розриву створіть нову кімнату. Прогрес одиночної гри збережено.": "Early two-player test. Direct connections may fail on some networks. No host migration; create a new room after a disconnect. Your single-player progress is safe.",
  "Швидкий український аркадний екшен із руйнуванням рівнів, історичними героями, чорним гумором і мультяшним хаосом.": "Fast Ukrainian arcade action with destructible levels, historical heroes, dark humor and cartoon chaos.",
  "Ранній безкоштовний прототип. Клавіатура, геймпад або сенсорні кнопки (мобільний тест). Одинадцять бійців, шість операцій. Збереження — у вашому браузері.": "An early free prototype. Keyboard, gamepad or touch controls (mobile test). Eleven fighters, six operations. Progress is saved in your browser.",
  "Автор:": "Created by:",
  "· команда UA Force.": "· the UA Force team.",
  "Якщо хочете допомогти нам продовжувати розробку, можете підтримати проєкт. Гра залишається безкоштовною.": "Want to help us keep building? You can support development. The game stays free.",
  "Підтримати розробку ↗": "Support development ↗",
  "Рахуємо знеособлені події запуску, проходження та коопу через Cloudflare. Без кодів кімнат і особистих даних.": "We count anonymous launch, completion and co-op events through Cloudflare. No room codes or personal data.",
  "Вимкнути ігрову аналітику": "Disable gameplay analytics",
  "Початкова публічна демоверсія · вересень 2026": "First public demo · September 2026",
  "Наступна операція": "Next operation",
  "Герой: Тарас Шевченко": "Hero: Taras Shevchenko",
  "УСІ БІЙЦІ": "ALL FIGHTERS",
  "Випробування": "Practice",
  "Обери бійця. Прогрес кампанії збережено. У паузі можна обрати іншого або почати випробування заново.": "Choose a fighter. Campaign progress is safe. Use pause to pick another fighter or restart practice.",
  "НАЛАШТУВАННЯ": "SETTINGS",
  "Керування та звук": "Controls and audio",
  "Готово": "Done",
  "Увімкнено": "On",
  "Вимкнено": "Off",
  "Наближення сцени": "Scene zoom",
  "На телефоні сцена більша. У кооперативі камера віддаляється, коли ви розходитеся. 100% — повний огляд.": "The scene is larger on phones. In co-op, the camera zooms out when you move apart. 100% shows the full view.",
  "На екрані: стик — рух і драбини; ✕ — стрибок; □ — взаємодія. Значки праворуч — атака, спецприйом та ульта. Можна бігти, стріляти й стрибати одночасно.": "On screen: stick — movement and ladders; ✕ — jump; □ — interact. Icons on the right — attack, special and ultimate. You can move, fire and jump together.",
  "Підключіть геймпад і натисніть будь-яку кнопку на активній вкладці.": "Connect a gamepad and press any button while this tab is active.",
  "Активний контролер": "Active controller",
  "Дія": "Action",
  "Клавіша": "Key",
  "Геймпад": "Gamepad",
  "Розмір інтерфейсу": "Interface size",
  "Зменшити рух заставок": "Reduce reveal motion",
  "Вісь руху": "Movement axis",
  "Мертва зона": "Dead zone",
  "Загальна гучність": "Master volume",
  "Ефекти": "Effects",
  "Музика й рифи": "Music and riffs",
  "Анаунсер": "Announcer",
  "Фонова музика: дослідження / бій": "Background music: exploration / combat",
  "Біля бочки: взаємодія — підняти / кинути; вниз + взаємодія — скинути. Бочка вибухає від сильного удару.": "Near a barrel: interact to pick up / throw; down + interact to drop. Barrels explode on a hard impact.",
  "Стріляйте в бік останнього руху. Для пострілу вище — стрибніть.": "Shoot in the direction you last moved. Jump to shoot higher.",
  "Біля стіни: тримайте напрямок до неї та стрибок, щоб карабкатися. Відпустіть і натисніть стрибок знову, щоб відштовхнутися.": "At a wall: hold toward it and hold jump to climb. Release and press jump again to push off.",
  "W/S або ↑/↓ — драбини. Відпустіть стік, щоб зупинитися на драбині; стрибок відчіплює героя.": "W/S or ↑/↓ — ladders. Release the stick to hold position; jump to let go.",
  "Під час налаштування гра стоїть на паузі.": "The game pauses while you change settings.",
  "Голос бійця": "Fighter voice",
  "Синтезований український анаунсер. Усі одинадцять бійців мають власне оголошення. Бандер-Бро — альтернативне ім’я Степана Бандери.": "Ukrainian synthesized announcer. All eleven fighters have their own introductions. Bander-Bro is an alternative name for Stepan Bandera.",
  "Репліка": "Voice line",
  "Прослухати вихід": "Preview introduction",
  "Зупинити звук": "Stop audio",
  "Скинути керування": "Reset controls",
  "Ігрове поле UA Force": "UA Force game field",
  "Відкрити налаштування керування": "Open control settings",
  "Пауза": "Pause",
  "Цілі операції": "Operation objectives",
  "Поточний герой": "Current hero",
  "Зброя та вміння": "Weapons and abilities",
  "Увімкнути музику": "Enable music",
  "Меню паузи": "Pause menu",
  "Закрити налаштування": "Close settings",
  "Поточні кнопки та осі геймпада": "Current gamepad buttons and axes",
  "Мова": "Language",
  "Мова інтерфейсу": "Interface language",
  "Озвучка залишається українською.": "Voice audio remains Ukrainian.",
  "Форма звіту наразі українською; опис можна написати англійською.": "The report form is currently in Ukrainian; you can write your report in English."
};
