// Generated by tools/pack-local-sfx.py; provenance: docs/COMBAT_SFX_ASSETS.json.
export const SFX_BANK = "/assets/audio/sfx/combat-bank.wav";
export const SFX_ASSETS = {
  "shevchenko-weapon-0": {
    "offset": 0.0,
    "seconds": 0.415875
  },
  "shevchenko-weapon-1": {
    "offset": 0.455875,
    "seconds": 0.40570833333333334
  },
  "shevchenko-weapon-2": {
    "offset": 0.9015833333333333,
    "seconds": 0.39608333333333334
  },
  "lesya-weapon-0": {
    "offset": 1.3376666666666666,
    "seconds": 0.36
  },
  "lesya-weapon-1": {
    "offset": 1.7376666666666667,
    "seconds": 0.36
  },
  "lesya-weapon-2": {
    "offset": 2.1376666666666666,
    "seconds": 0.36
  },
  "franko-weapon-0": {
    "offset": 2.5376666666666665,
    "seconds": 0.32
  },
  "franko-weapon-1": {
    "offset": 2.897666666666667,
    "seconds": 0.32
  },
  "franko-weapon-2": {
    "offset": 3.2576666666666667,
    "seconds": 0.32
  },
  "bandera-weapon-0": {
    "offset": 3.6176666666666666,
    "seconds": 0.174125
  },
  "bandera-weapon-1": {
    "offset": 3.8317916666666667,
    "seconds": 0.17
  },
  "bandera-weapon-2": {
    "offset": 4.041791666666667,
    "seconds": 0.166125
  },
  "mamai-weapon-0": {
    "offset": 4.247916666666667,
    "seconds": 0.5485
  },
  "mamai-weapon-1": {
    "offset": 4.836416666666667,
    "seconds": 0.535
  },
  "mamai-weapon-2": {
    "offset": 5.411416666666667,
    "seconds": 0.5222083333333334
  },
  "mamai-melee-weapon-0": {
    "offset": 5.973625,
    "seconds": 0.28
  },
  "mamai-melee-weapon-1": {
    "offset": 6.293625,
    "seconds": 0.28
  },
  "mamai-melee-weapon-2": {
    "offset": 6.613625,
    "seconds": 0.28
  },
  "bayraktar-weapon-0": {
    "offset": 6.933625,
    "seconds": 0.3617916666666667
  },
  "bayraktar-weapon-1": {
    "offset": 7.335416666666666,
    "seconds": 0.3529583333333333
  },
  "bayraktar-weapon-2": {
    "offset": 7.728375,
    "seconds": 0.34
  },
  "ghost-weapon-0": {
    "offset": 8.108375,
    "seconds": 0.24591666666666667
  },
  "ghost-weapon-1": {
    "offset": 8.394291666666666,
    "seconds": 0.24
  },
  "ghost-weapon-2": {
    "offset": 8.674291666666667,
    "seconds": 0.23441666666666666
  },
  "zelensky-weapon-0": {
    "offset": 8.948708333333334,
    "seconds": 0.3177083333333333
  },
  "zelensky-weapon-1": {
    "offset": 9.306416666666667,
    "seconds": 0.31
  },
  "zelensky-weapon-2": {
    "offset": 9.656416666666667,
    "seconds": 0.30270833333333336
  },
  "bilozerska-weapon-0": {
    "offset": 9.999125,
    "seconds": 0.8818333333333334
  },
  "bilozerska-weapon-1": {
    "offset": 10.920958333333333,
    "seconds": 0.86
  },
  "bilozerska-weapon-2": {
    "offset": 11.820958333333333,
    "seconds": 0.8392916666666667
  },
  "it-army-weapon-0": {
    "offset": 12.70025,
    "seconds": 0.5
  },
  "it-army-weapon-1": {
    "offset": 13.24025,
    "seconds": 0.5
  },
  "it-army-weapon-2": {
    "offset": 13.78025,
    "seconds": 0.5
  },
  "skovoroda-weapon-0": {
    "offset": 14.32025,
    "seconds": 0.3
  },
  "skovoroda-weapon-1": {
    "offset": 14.66025,
    "seconds": 0.3
  },
  "skovoroda-weapon-2": {
    "offset": 15.00025,
    "seconds": 0.3
  },
  "shevchenko-hit": {
    "offset": 15.34025,
    "seconds": 0.42
  },
  "lesya-hit": {
    "offset": 15.80025,
    "seconds": 0.42
  },
  "franko-hit": {
    "offset": 16.26025,
    "seconds": 0.55
  },
  "bandera-hit": {
    "offset": 16.85025,
    "seconds": 0.42
  },
  "mamai-hit": {
    "offset": 17.31025,
    "seconds": 0.42
  },
  "bayraktar-hit": {
    "offset": 17.77025,
    "seconds": 0.42
  },
  "ghost-hit": {
    "offset": 18.23025,
    "seconds": 0.42
  },
  "zelensky-hit": {
    "offset": 18.69025,
    "seconds": 0.42
  },
  "bilozerska-hit": {
    "offset": 19.15025,
    "seconds": 0.42
  },
  "it-army-hit": {
    "offset": 19.61025,
    "seconds": 0.42
  },
  "skovoroda-hit": {
    "offset": 20.07025,
    "seconds": 0.5
  },
  "ricochet": {
    "offset": 20.61025,
    "seconds": 0.45
  },
  "explosion": {
    "offset": 21.10025,
    "seconds": 1.3
  },
  "glass-fire": {
    "offset": 22.44025,
    "seconds": 0.7
  },
  "roots": {
    "offset": 23.18025,
    "seconds": 0.8
  },
  "stone-hit": {
    "offset": 24.02025,
    "seconds": 0.55
  },
  "thunder": {
    "offset": 24.61025,
    "seconds": 1.3
  },
  "rail-shot": {
    "offset": 25.95025,
    "seconds": 1.1
  },
  "bolt": {
    "offset": 27.09025,
    "seconds": 0.4
  },
  "mine-arm": {
    "offset": 27.53025,
    "seconds": 0.22
  },
  "rocket": {
    "offset": 27.79025,
    "seconds": 0.65
  },
  "shevchenko-special": {
    "offset": 28.48025,
    "seconds": 1.2
  },
  "lesya-special": {
    "offset": 29.72025,
    "seconds": 0.8
  },
  "lesya-ultimate": {
    "offset": 30.56025,
    "seconds": 1.1
  },
  "franko-special": {
    "offset": 31.70025,
    "seconds": 0.8
  },
  "franko-ultimate": {
    "offset": 32.54025,
    "seconds": 0.985
  },
  "bandera-special": {
    "offset": 33.56525,
    "seconds": 0.34
  },
  "bandera-ultimate": {
    "offset": 33.94525,
    "seconds": 1.3
  },
  "mamai-special": {
    "offset": 35.28525,
    "seconds": 0.45
  },
  "mamai-ultimate": {
    "offset": 35.77525,
    "seconds": 1.3
  },
  "bayraktar-special": {
    "offset": 37.11525,
    "seconds": 0.7
  },
  "bayraktar-ultimate": {
    "offset": 37.85525,
    "seconds": 0.9433333333333334
  },
  "ghost-special": {
    "offset": 38.83858333333333,
    "seconds": 0.51
  },
  "ghost-ultimate": {
    "offset": 39.38858333333334,
    "seconds": 1.8
  },
  "zelensky-special": {
    "offset": 41.22858333333333,
    "seconds": 0.25
  },
  "zelensky-ultimate": {
    "offset": 41.51858333333333,
    "seconds": 1.0
  },
  "bilozerska-special": {
    "offset": 42.55858333333333,
    "seconds": 0.25
  },
  "bilozerska-ultimate": {
    "offset": 42.84858333333333,
    "seconds": 1.1
  },
  "it-army-special": {
    "offset": 43.98858333333333,
    "seconds": 0.4
  },
  "it-army-ultimate": {
    "offset": 44.428583333333336,
    "seconds": 1.2
  },
  "skovoroda-special": {
    "offset": 45.66858333333333,
    "seconds": 0.6
  },
  "skovoroda-ultimate": {
    "offset": 46.30858333333333,
    "seconds": 0.9
  },
  "shevchenko-ultimate": {
    "offset": 47.248583333333336,
    "seconds": 1.3
  },
  "lesya-special-loop": {
    "offset": 48.58858333333333,
    "seconds": 1.75
  },
  "lesya-ultimate-loop": {
    "offset": 50.37858333333333,
    "seconds": 1.75
  },
  "franko-special-loop": {
    "offset": 52.16858333333333,
    "seconds": 1.75
  },
  "bandera-special-loop": {
    "offset": 53.95858333333333,
    "seconds": 1.75
  },
  "bandera-ultimate-loop": {
    "offset": 55.748583333333336,
    "seconds": 1.75
  },
  "mamai-special-loop": {
    "offset": 57.538583333333335,
    "seconds": 0.95
  },
  "mamai-ultimate-loop": {
    "offset": 58.52858333333333,
    "seconds": 0.95
  },
  "bayraktar-special-loop": {
    "offset": 59.51858333333333,
    "seconds": 1.75
  },
  "bayraktar-ultimate-loop": {
    "offset": 61.30858333333333,
    "seconds": 1.75
  },
  "ghost-ultimate-loop": {
    "offset": 63.09858333333333,
    "seconds": 1.75
  },
  "zelensky-ultimate-loop": {
    "offset": 64.88858333333333,
    "seconds": 1.75
  },
  "it-army-ultimate-loop": {
    "offset": 66.67858333333334,
    "seconds": 1.75
  },
  "skovoroda-special-loop": {
    "offset": 68.46858333333333,
    "seconds": 1.75
  },
  "skovoroda-ultimate-loop": {
    "offset": 70.25858333333333,
    "seconds": 1.75
  },
  "shevchenko-special-end": {
    "offset": 72.04858333333334,
    "seconds": 0.35
  },
  "shevchenko-ultimate-end": {
    "offset": 72.43858333333333,
    "seconds": 0.35
  },
  "lesya-special-end": {
    "offset": 72.82858333333333,
    "seconds": 0.35
  },
  "lesya-ultimate-end": {
    "offset": 73.21858333333333,
    "seconds": 0.35
  },
  "franko-special-end": {
    "offset": 73.60858333333333,
    "seconds": 0.35
  },
  "franko-ultimate-end": {
    "offset": 73.99858333333333,
    "seconds": 0.35
  },
  "bandera-special-end": {
    "offset": 74.38858333333333,
    "seconds": 0.35
  },
  "bandera-ultimate-end": {
    "offset": 74.77858333333333,
    "seconds": 0.35
  },
  "mamai-special-end": {
    "offset": 75.16858333333333,
    "seconds": 0.35
  },
  "mamai-ultimate-end": {
    "offset": 75.55858333333333,
    "seconds": 0.35
  },
  "bayraktar-special-end": {
    "offset": 75.94858333333333,
    "seconds": 0.35
  },
  "bayraktar-ultimate-end": {
    "offset": 76.33858333333333,
    "seconds": 0.35
  },
  "ghost-special-end": {
    "offset": 76.72858333333333,
    "seconds": 0.35
  },
  "ghost-ultimate-end": {
    "offset": 77.11858333333333,
    "seconds": 0.35
  },
  "zelensky-special-end": {
    "offset": 77.50858333333333,
    "seconds": 0.35
  },
  "zelensky-ultimate-end": {
    "offset": 77.89858333333333,
    "seconds": 0.35
  },
  "bilozerska-special-end": {
    "offset": 78.28858333333334,
    "seconds": 0.35
  },
  "bilozerska-ultimate-end": {
    "offset": 78.67858333333334,
    "seconds": 0.35
  },
  "it-army-special-end": {
    "offset": 79.06858333333334,
    "seconds": 0.35
  },
  "it-army-ultimate-end": {
    "offset": 79.45858333333334,
    "seconds": 0.35
  },
  "skovoroda-special-end": {
    "offset": 79.84858333333334,
    "seconds": 0.35
  },
  "skovoroda-ultimate-end": {
    "offset": 80.23858333333334,
    "seconds": 0.35
  },
  "lesya-reload": {
    "offset": 80.62858333333334,
    "seconds": 1.2799583333333333
  },
  "lesya-reload-end": {
    "offset": 81.94854166666667,
    "seconds": 0.2
  },
  "bandera-reload": {
    "offset": 82.18854166666667,
    "seconds": 2.2799583333333335
  },
  "bandera-reload-end": {
    "offset": 84.5085,
    "seconds": 0.2
  },
  "mamai-reload": {
    "offset": 84.7485,
    "seconds": 2.6799583333333334
  },
  "mamai-reload-end": {
    "offset": 87.46845833333333,
    "seconds": 0.2
  },
  "bayraktar-reload": {
    "offset": 87.70845833333334,
    "seconds": 2.88
  },
  "bayraktar-reload-end": {
    "offset": 90.62845833333333,
    "seconds": 0.2
  },
  "ghost-reload": {
    "offset": 90.86845833333334,
    "seconds": 1.98
  },
  "ghost-reload-end": {
    "offset": 92.88845833333333,
    "seconds": 0.2
  },
  "zelensky-reload": {
    "offset": 93.12845833333333,
    "seconds": 1.68
  },
  "zelensky-reload-end": {
    "offset": 94.84845833333334,
    "seconds": 0.2
  },
  "bilozerska-reload": {
    "offset": 95.08845833333334,
    "seconds": 4.68
  },
  "bilozerska-reload-end": {
    "offset": 99.80845833333333,
    "seconds": 0.2
  },
  "it-army-reload": {
    "offset": 100.04845833333333,
    "seconds": 1.88
  },
  "it-army-reload-end": {
    "offset": 101.96845833333333,
    "seconds": 0.2
  },
  "support-infantry": {
    "offset": 102.20845833333334,
    "seconds": 0.21
  },
  "support-turret": {
    "offset": 102.45845833333334,
    "seconds": 0.23
  },
  "turret-step": {
    "offset": 102.72845833333334,
    "seconds": 0.3529583333333333
  },
  "follower-hurt": {
    "offset": 103.12141666666666,
    "seconds": 0.22908333333333333
  },
  "follower-down": {
    "offset": 103.3905,
    "seconds": 0.6
  },
  "barrel-lift": {
    "offset": 104.0305,
    "seconds": 0.6039583333333334
  },
  "barrel-throw": {
    "offset": 104.67445833333333,
    "seconds": 0.35
  },
  "armor-hit": {
    "offset": 105.06445833333333,
    "seconds": 0.3
  },
  "tank-land": {
    "offset": 105.40445833333334,
    "seconds": 0.65
  },
  "tank-jump": {
    "offset": 106.09445833333334,
    "seconds": 0.6
  },
  "hatch": {
    "offset": 106.73445833333334,
    "seconds": 0.39591666666666664
  },
  "tank-shot": {
    "offset": 107.170375,
    "seconds": 1.2407916666666667
  },
  "tank-engine": {
    "offset": 108.45116666666667,
    "seconds": 2.5
  },
  "plane-engine": {
    "offset": 110.99116666666667,
    "seconds": 1.8
  },
  "drone-engine": {
    "offset": 112.83116666666666,
    "seconds": 1.75
  },
  "drone-dive": {
    "offset": 114.62116666666667,
    "seconds": 0.65
  },
  "enemy-alert": {
    "offset": 115.31116666666667,
    "seconds": 0.15708333333333332
  },
  "enemy-fuse": {
    "offset": 115.50825,
    "seconds": 0.75
  },
  "pickup": {
    "offset": 116.29825,
    "seconds": 0.207625
  },
  "debris": {
    "offset": 116.545875,
    "seconds": 0.289875
  },
  "foley-shevchenko-step-0": {
    "offset": 116.87575,
    "seconds": 0.2
  },
  "foley-shevchenko-step-1": {
    "offset": 117.11575,
    "seconds": 0.2
  },
  "foley-shevchenko-step-2": {
    "offset": 117.35575,
    "seconds": 0.2
  },
  "foley-shevchenko-climb-0": {
    "offset": 117.59575,
    "seconds": 0.2
  },
  "foley-shevchenko-climb-1": {
    "offset": 117.83575,
    "seconds": 0.2
  },
  "foley-shevchenko-climb-2": {
    "offset": 118.07575,
    "seconds": 0.2
  },
  "foley-shevchenko-jump-0": {
    "offset": 118.31575,
    "seconds": 0.2
  },
  "foley-shevchenko-jump-1": {
    "offset": 118.55575,
    "seconds": 0.2
  },
  "foley-shevchenko-jump-2": {
    "offset": 118.79575,
    "seconds": 0.2
  },
  "foley-shevchenko-land-0": {
    "offset": 119.03575,
    "seconds": 0.26
  },
  "foley-shevchenko-land-1": {
    "offset": 119.33575,
    "seconds": 0.26
  },
  "foley-shevchenko-land-2": {
    "offset": 119.63575,
    "seconds": 0.26
  },
  "foley-shevchenko-hurt-0": {
    "offset": 119.93575,
    "seconds": 0.2
  },
  "foley-shevchenko-hurt-1": {
    "offset": 120.17575,
    "seconds": 0.2
  },
  "foley-shevchenko-hurt-2": {
    "offset": 120.41575,
    "seconds": 0.2
  },
  "foley-shevchenko-ready-0": {
    "offset": 120.65575,
    "seconds": 0.2
  },
  "foley-shevchenko-ready-1": {
    "offset": 120.89575,
    "seconds": 0.2
  },
  "foley-shevchenko-ready-2": {
    "offset": 121.13575,
    "seconds": 0.2
  },
  "foley-lesya-step-0": {
    "offset": 121.37575,
    "seconds": 0.2
  },
  "foley-lesya-step-1": {
    "offset": 121.61575,
    "seconds": 0.2
  },
  "foley-lesya-step-2": {
    "offset": 121.85575,
    "seconds": 0.2
  },
  "foley-lesya-climb-0": {
    "offset": 122.09575,
    "seconds": 0.2
  },
  "foley-lesya-climb-1": {
    "offset": 122.33575,
    "seconds": 0.2
  },
  "foley-lesya-climb-2": {
    "offset": 122.57575,
    "seconds": 0.2
  },
  "foley-lesya-jump-0": {
    "offset": 122.81575,
    "seconds": 0.2
  },
  "foley-lesya-jump-1": {
    "offset": 123.05575,
    "seconds": 0.2
  },
  "foley-lesya-jump-2": {
    "offset": 123.29575,
    "seconds": 0.2
  },
  "foley-lesya-land-0": {
    "offset": 123.53575,
    "seconds": 0.26
  },
  "foley-lesya-land-1": {
    "offset": 123.83575,
    "seconds": 0.26
  },
  "foley-lesya-land-2": {
    "offset": 124.13575,
    "seconds": 0.26
  },
  "foley-lesya-hurt-0": {
    "offset": 124.43575,
    "seconds": 0.2
  },
  "foley-lesya-hurt-1": {
    "offset": 124.67575,
    "seconds": 0.2
  },
  "foley-lesya-hurt-2": {
    "offset": 124.91575,
    "seconds": 0.2
  },
  "foley-lesya-ready-0": {
    "offset": 125.15575,
    "seconds": 0.2
  },
  "foley-lesya-ready-1": {
    "offset": 125.39575,
    "seconds": 0.2
  },
  "foley-lesya-ready-2": {
    "offset": 125.63575,
    "seconds": 0.2
  },
  "foley-franko-step-0": {
    "offset": 125.87575,
    "seconds": 0.2
  },
  "foley-franko-step-1": {
    "offset": 126.11575,
    "seconds": 0.2
  },
  "foley-franko-step-2": {
    "offset": 126.35575,
    "seconds": 0.2
  },
  "foley-franko-climb-0": {
    "offset": 126.59575,
    "seconds": 0.2
  },
  "foley-franko-climb-1": {
    "offset": 126.83575,
    "seconds": 0.2
  },
  "foley-franko-climb-2": {
    "offset": 127.07575,
    "seconds": 0.2
  },
  "foley-franko-jump-0": {
    "offset": 127.31575,
    "seconds": 0.2
  },
  "foley-franko-jump-1": {
    "offset": 127.55575,
    "seconds": 0.2
  },
  "foley-franko-jump-2": {
    "offset": 127.79575,
    "seconds": 0.2
  },
  "foley-franko-land-0": {
    "offset": 128.03575,
    "seconds": 0.26
  },
  "foley-franko-land-1": {
    "offset": 128.33575,
    "seconds": 0.26
  },
  "foley-franko-land-2": {
    "offset": 128.63575,
    "seconds": 0.26
  },
  "foley-franko-hurt-0": {
    "offset": 128.93575,
    "seconds": 0.2
  },
  "foley-franko-hurt-1": {
    "offset": 129.17575,
    "seconds": 0.2
  },
  "foley-franko-hurt-2": {
    "offset": 129.41575,
    "seconds": 0.2
  },
  "foley-franko-ready-0": {
    "offset": 129.65575,
    "seconds": 0.2
  },
  "foley-franko-ready-1": {
    "offset": 129.89575,
    "seconds": 0.2
  },
  "foley-franko-ready-2": {
    "offset": 130.13575,
    "seconds": 0.2
  },
  "foley-bandera-step-0": {
    "offset": 130.37575,
    "seconds": 0.2
  },
  "foley-bandera-step-1": {
    "offset": 130.61575,
    "seconds": 0.2
  },
  "foley-bandera-step-2": {
    "offset": 130.85575,
    "seconds": 0.2
  },
  "foley-bandera-climb-0": {
    "offset": 131.09575,
    "seconds": 0.2
  },
  "foley-bandera-climb-1": {
    "offset": 131.33575,
    "seconds": 0.2
  },
  "foley-bandera-climb-2": {
    "offset": 131.57575,
    "seconds": 0.2
  },
  "foley-bandera-jump-0": {
    "offset": 131.81575,
    "seconds": 0.2
  },
  "foley-bandera-jump-1": {
    "offset": 132.05575,
    "seconds": 0.2
  },
  "foley-bandera-jump-2": {
    "offset": 132.29575,
    "seconds": 0.2
  },
  "foley-bandera-land-0": {
    "offset": 132.53575,
    "seconds": 0.26
  },
  "foley-bandera-land-1": {
    "offset": 132.83575,
    "seconds": 0.26
  },
  "foley-bandera-land-2": {
    "offset": 133.13575,
    "seconds": 0.26
  },
  "foley-bandera-hurt-0": {
    "offset": 133.43575,
    "seconds": 0.2
  },
  "foley-bandera-hurt-1": {
    "offset": 133.67575,
    "seconds": 0.2
  },
  "foley-bandera-hurt-2": {
    "offset": 133.91575,
    "seconds": 0.2
  },
  "foley-bandera-ready-0": {
    "offset": 134.15575,
    "seconds": 0.2
  },
  "foley-bandera-ready-1": {
    "offset": 134.39575,
    "seconds": 0.2
  },
  "foley-bandera-ready-2": {
    "offset": 134.63575,
    "seconds": 0.2
  },
  "foley-mamai-step-0": {
    "offset": 134.87575,
    "seconds": 0.2
  },
  "foley-mamai-step-1": {
    "offset": 135.11575,
    "seconds": 0.2
  },
  "foley-mamai-step-2": {
    "offset": 135.35575,
    "seconds": 0.2
  },
  "foley-mamai-climb-0": {
    "offset": 135.59575,
    "seconds": 0.2
  },
  "foley-mamai-climb-1": {
    "offset": 135.83575,
    "seconds": 0.2
  },
  "foley-mamai-climb-2": {
    "offset": 136.07575,
    "seconds": 0.2
  },
  "foley-mamai-jump-0": {
    "offset": 136.31575,
    "seconds": 0.2
  },
  "foley-mamai-jump-1": {
    "offset": 136.55575,
    "seconds": 0.2
  },
  "foley-mamai-jump-2": {
    "offset": 136.79575,
    "seconds": 0.2
  },
  "foley-mamai-land-0": {
    "offset": 137.03575,
    "seconds": 0.26
  },
  "foley-mamai-land-1": {
    "offset": 137.33575,
    "seconds": 0.26
  },
  "foley-mamai-land-2": {
    "offset": 137.63575,
    "seconds": 0.26
  },
  "foley-mamai-hurt-0": {
    "offset": 137.93575,
    "seconds": 0.2
  },
  "foley-mamai-hurt-1": {
    "offset": 138.17575,
    "seconds": 0.2
  },
  "foley-mamai-hurt-2": {
    "offset": 138.41575,
    "seconds": 0.2
  },
  "foley-mamai-ready-0": {
    "offset": 138.65575,
    "seconds": 0.2
  },
  "foley-mamai-ready-1": {
    "offset": 138.89575,
    "seconds": 0.2
  },
  "foley-mamai-ready-2": {
    "offset": 139.13575,
    "seconds": 0.2
  },
  "foley-bayraktar-step-0": {
    "offset": 139.37575,
    "seconds": 0.2
  },
  "foley-bayraktar-step-1": {
    "offset": 139.61575,
    "seconds": 0.2
  },
  "foley-bayraktar-step-2": {
    "offset": 139.85575,
    "seconds": 0.2
  },
  "foley-bayraktar-climb-0": {
    "offset": 140.09575,
    "seconds": 0.2
  },
  "foley-bayraktar-climb-1": {
    "offset": 140.33575,
    "seconds": 0.2
  },
  "foley-bayraktar-climb-2": {
    "offset": 140.57575,
    "seconds": 0.2
  },
  "foley-bayraktar-jump-0": {
    "offset": 140.81575,
    "seconds": 0.2
  },
  "foley-bayraktar-jump-1": {
    "offset": 141.05575,
    "seconds": 0.2
  },
  "foley-bayraktar-jump-2": {
    "offset": 141.29575,
    "seconds": 0.2
  },
  "foley-bayraktar-land-0": {
    "offset": 141.53575,
    "seconds": 0.26
  },
  "foley-bayraktar-land-1": {
    "offset": 141.83575,
    "seconds": 0.26
  },
  "foley-bayraktar-land-2": {
    "offset": 142.13575,
    "seconds": 0.26
  },
  "foley-bayraktar-hurt-0": {
    "offset": 142.43575,
    "seconds": 0.2
  },
  "foley-bayraktar-hurt-1": {
    "offset": 142.67575,
    "seconds": 0.2
  },
  "foley-bayraktar-hurt-2": {
    "offset": 142.91575,
    "seconds": 0.2
  },
  "foley-bayraktar-ready-0": {
    "offset": 143.15575,
    "seconds": 0.2
  },
  "foley-bayraktar-ready-1": {
    "offset": 143.39575,
    "seconds": 0.2
  },
  "foley-bayraktar-ready-2": {
    "offset": 143.63575,
    "seconds": 0.2
  },
  "foley-ghost-step-0": {
    "offset": 143.87575,
    "seconds": 0.2
  },
  "foley-ghost-step-1": {
    "offset": 144.11575,
    "seconds": 0.2
  },
  "foley-ghost-step-2": {
    "offset": 144.35575,
    "seconds": 0.2
  },
  "foley-ghost-climb-0": {
    "offset": 144.59575,
    "seconds": 0.2
  },
  "foley-ghost-climb-1": {
    "offset": 144.83575,
    "seconds": 0.2
  },
  "foley-ghost-climb-2": {
    "offset": 145.07575,
    "seconds": 0.2
  },
  "foley-ghost-jump-0": {
    "offset": 145.31575,
    "seconds": 0.2
  },
  "foley-ghost-jump-1": {
    "offset": 145.55575,
    "seconds": 0.2
  },
  "foley-ghost-jump-2": {
    "offset": 145.79575,
    "seconds": 0.2
  },
  "foley-ghost-land-0": {
    "offset": 146.03575,
    "seconds": 0.26
  },
  "foley-ghost-land-1": {
    "offset": 146.33575,
    "seconds": 0.26
  },
  "foley-ghost-land-2": {
    "offset": 146.63575,
    "seconds": 0.26
  },
  "foley-ghost-hurt-0": {
    "offset": 146.93575,
    "seconds": 0.2
  },
  "foley-ghost-hurt-1": {
    "offset": 147.17575,
    "seconds": 0.2
  },
  "foley-ghost-hurt-2": {
    "offset": 147.41575,
    "seconds": 0.2
  },
  "foley-ghost-ready-0": {
    "offset": 147.65575,
    "seconds": 0.2
  },
  "foley-ghost-ready-1": {
    "offset": 147.89575,
    "seconds": 0.2
  },
  "foley-ghost-ready-2": {
    "offset": 148.13575,
    "seconds": 0.2
  },
  "foley-zelensky-step-0": {
    "offset": 148.37575,
    "seconds": 0.2
  },
  "foley-zelensky-step-1": {
    "offset": 148.61575,
    "seconds": 0.2
  },
  "foley-zelensky-step-2": {
    "offset": 148.85575,
    "seconds": 0.2
  },
  "foley-zelensky-climb-0": {
    "offset": 149.09575,
    "seconds": 0.2
  },
  "foley-zelensky-climb-1": {
    "offset": 149.33575,
    "seconds": 0.2
  },
  "foley-zelensky-climb-2": {
    "offset": 149.57575,
    "seconds": 0.2
  },
  "foley-zelensky-jump-0": {
    "offset": 149.81575,
    "seconds": 0.2
  },
  "foley-zelensky-jump-1": {
    "offset": 150.05575,
    "seconds": 0.2
  },
  "foley-zelensky-jump-2": {
    "offset": 150.29575,
    "seconds": 0.2
  },
  "foley-zelensky-land-0": {
    "offset": 150.53575,
    "seconds": 0.26
  },
  "foley-zelensky-land-1": {
    "offset": 150.83575,
    "seconds": 0.26
  },
  "foley-zelensky-land-2": {
    "offset": 151.13575,
    "seconds": 0.26
  },
  "foley-zelensky-hurt-0": {
    "offset": 151.43575,
    "seconds": 0.2
  },
  "foley-zelensky-hurt-1": {
    "offset": 151.67575,
    "seconds": 0.2
  },
  "foley-zelensky-hurt-2": {
    "offset": 151.91575,
    "seconds": 0.2
  },
  "foley-zelensky-ready-0": {
    "offset": 152.15575,
    "seconds": 0.2
  },
  "foley-zelensky-ready-1": {
    "offset": 152.39575,
    "seconds": 0.2
  },
  "foley-zelensky-ready-2": {
    "offset": 152.63575,
    "seconds": 0.2
  },
  "foley-bilozerska-step-0": {
    "offset": 152.87575,
    "seconds": 0.2
  },
  "foley-bilozerska-step-1": {
    "offset": 153.11575,
    "seconds": 0.2
  },
  "foley-bilozerska-step-2": {
    "offset": 153.35575,
    "seconds": 0.2
  },
  "foley-bilozerska-climb-0": {
    "offset": 153.59575,
    "seconds": 0.2
  },
  "foley-bilozerska-climb-1": {
    "offset": 153.83575,
    "seconds": 0.2
  },
  "foley-bilozerska-climb-2": {
    "offset": 154.07575,
    "seconds": 0.2
  },
  "foley-bilozerska-jump-0": {
    "offset": 154.31575,
    "seconds": 0.2
  },
  "foley-bilozerska-jump-1": {
    "offset": 154.55575,
    "seconds": 0.2
  },
  "foley-bilozerska-jump-2": {
    "offset": 154.79575,
    "seconds": 0.2
  },
  "foley-bilozerska-land-0": {
    "offset": 155.03575,
    "seconds": 0.26
  },
  "foley-bilozerska-land-1": {
    "offset": 155.33575,
    "seconds": 0.26
  },
  "foley-bilozerska-land-2": {
    "offset": 155.63575,
    "seconds": 0.26
  },
  "foley-bilozerska-hurt-0": {
    "offset": 155.93575,
    "seconds": 0.2
  },
  "foley-bilozerska-hurt-1": {
    "offset": 156.17575,
    "seconds": 0.2
  },
  "foley-bilozerska-hurt-2": {
    "offset": 156.41575,
    "seconds": 0.2
  },
  "foley-bilozerska-ready-0": {
    "offset": 156.65575,
    "seconds": 0.2
  },
  "foley-bilozerska-ready-1": {
    "offset": 156.89575,
    "seconds": 0.2
  },
  "foley-bilozerska-ready-2": {
    "offset": 157.13575,
    "seconds": 0.2
  },
  "foley-it-army-step-0": {
    "offset": 157.37575,
    "seconds": 0.2
  },
  "foley-it-army-step-1": {
    "offset": 157.61575,
    "seconds": 0.2
  },
  "foley-it-army-step-2": {
    "offset": 157.85575,
    "seconds": 0.2
  },
  "foley-it-army-climb-0": {
    "offset": 158.09575,
    "seconds": 0.2
  },
  "foley-it-army-climb-1": {
    "offset": 158.33575,
    "seconds": 0.2
  },
  "foley-it-army-climb-2": {
    "offset": 158.57575,
    "seconds": 0.2
  },
  "foley-it-army-jump-0": {
    "offset": 158.81575,
    "seconds": 0.2
  },
  "foley-it-army-jump-1": {
    "offset": 159.05575,
    "seconds": 0.2
  },
  "foley-it-army-jump-2": {
    "offset": 159.29575,
    "seconds": 0.2
  },
  "foley-it-army-land-0": {
    "offset": 159.53575,
    "seconds": 0.26
  },
  "foley-it-army-land-1": {
    "offset": 159.83575,
    "seconds": 0.26
  },
  "foley-it-army-land-2": {
    "offset": 160.13575,
    "seconds": 0.26
  },
  "foley-it-army-hurt-0": {
    "offset": 160.43575,
    "seconds": 0.2
  },
  "foley-it-army-hurt-1": {
    "offset": 160.67575,
    "seconds": 0.2
  },
  "foley-it-army-hurt-2": {
    "offset": 160.91575,
    "seconds": 0.2
  },
  "foley-it-army-ready-0": {
    "offset": 161.15575,
    "seconds": 0.2
  },
  "foley-it-army-ready-1": {
    "offset": 161.39575,
    "seconds": 0.2
  },
  "foley-it-army-ready-2": {
    "offset": 161.63575,
    "seconds": 0.2
  },
  "foley-skovoroda-step-0": {
    "offset": 161.87575,
    "seconds": 0.2
  },
  "foley-skovoroda-step-1": {
    "offset": 162.11575,
    "seconds": 0.2
  },
  "foley-skovoroda-step-2": {
    "offset": 162.35575,
    "seconds": 0.2
  },
  "foley-skovoroda-climb-0": {
    "offset": 162.59575,
    "seconds": 0.2
  },
  "foley-skovoroda-climb-1": {
    "offset": 162.83575,
    "seconds": 0.2
  },
  "foley-skovoroda-climb-2": {
    "offset": 163.07575,
    "seconds": 0.2
  },
  "foley-skovoroda-jump-0": {
    "offset": 163.31575,
    "seconds": 0.2
  },
  "foley-skovoroda-jump-1": {
    "offset": 163.55575,
    "seconds": 0.2
  },
  "foley-skovoroda-jump-2": {
    "offset": 163.79575,
    "seconds": 0.2
  },
  "foley-skovoroda-land-0": {
    "offset": 164.03575,
    "seconds": 0.26
  },
  "foley-skovoroda-land-1": {
    "offset": 164.33575,
    "seconds": 0.26
  },
  "foley-skovoroda-land-2": {
    "offset": 164.63575,
    "seconds": 0.26
  },
  "foley-skovoroda-hurt-0": {
    "offset": 164.93575,
    "seconds": 0.2
  },
  "foley-skovoroda-hurt-1": {
    "offset": 165.17575,
    "seconds": 0.2
  },
  "foley-skovoroda-hurt-2": {
    "offset": 165.41575,
    "seconds": 0.2
  },
  "foley-skovoroda-ready-0": {
    "offset": 165.65575,
    "seconds": 0.2
  },
  "foley-skovoroda-ready-1": {
    "offset": 165.89575,
    "seconds": 0.2
  },
  "foley-skovoroda-ready-2": {
    "offset": 166.13575,
    "seconds": 0.2
  },
  "legacy-shot": {
    "offset": 166.37575,
    "seconds": 0.5
  },
  "legacy-hurt": {
    "offset": 166.91575,
    "seconds": 0.55
  },
  "legacy-reload": {
    "offset": 167.50575,
    "seconds": 0.5
  },
  "legacy-rescue": {
    "offset": 168.04575,
    "seconds": 0.5
  },
  "death-rifle-0": {
    "offset": 168.58575,
    "seconds": 0.8
  },
  "death-rifle-1": {
    "offset": 169.42575,
    "seconds": 0.8
  },
  "death-rifle-2": {
    "offset": 170.26575,
    "seconds": 0.8
  },
  "death-assault-0": {
    "offset": 171.10575,
    "seconds": 0.8
  },
  "death-assault-1": {
    "offset": 171.94575,
    "seconds": 0.8
  },
  "death-assault-2": {
    "offset": 172.78575,
    "seconds": 0.8
  },
  "death-gunner-0": {
    "offset": 173.62575,
    "seconds": 0.8
  },
  "death-gunner-1": {
    "offset": 174.46575,
    "seconds": 0.8
  },
  "death-gunner-2": {
    "offset": 175.30575,
    "seconds": 0.8
  },
  "death-sniper-0": {
    "offset": 176.14575,
    "seconds": 0.8
  },
  "death-sniper-1": {
    "offset": 176.98575,
    "seconds": 0.8
  },
  "death-sniper-2": {
    "offset": 177.82575,
    "seconds": 0.8
  },
  "death-scout-0": {
    "offset": 178.66575,
    "seconds": 0.8
  },
  "death-scout-1": {
    "offset": 179.50575,
    "seconds": 0.8
  },
  "death-scout-2": {
    "offset": 180.34575,
    "seconds": 0.8
  },
  "death-shield-0": {
    "offset": 181.18575,
    "seconds": 0.8
  },
  "death-shield-1": {
    "offset": 182.02575,
    "seconds": 0.8
  },
  "death-shield-2": {
    "offset": 182.86575,
    "seconds": 0.8
  },
  "death-demolition-0": {
    "offset": 183.70575,
    "seconds": 0.8
  },
  "death-demolition-1": {
    "offset": 184.54575,
    "seconds": 0.8
  },
  "death-demolition-2": {
    "offset": 185.38575,
    "seconds": 0.8
  },
  "gore-splat-0": {
    "offset": 186.22575,
    "seconds": 0.5
  },
  "gore-splat-1": {
    "offset": 186.76575,
    "seconds": 0.5
  },
  "gore-splat-2": {
    "offset": 187.30575,
    "seconds": 0.5
  },
  "gore-croak-0": {
    "offset": 187.84575,
    "seconds": 0.75
  },
  "gore-croak-1": {
    "offset": 188.63575,
    "seconds": 0.75
  },
  "gore-croak-2": {
    "offset": 189.42575,
    "seconds": 0.75
  },
  "gore-gib-land-0": {
    "offset": 190.21575,
    "seconds": 0.5
  },
  "gore-gib-land-1": {
    "offset": 190.75575,
    "seconds": 0.5
  },
  "gore-gib-land-2": {
    "offset": 191.29575,
    "seconds": 0.5
  },
  "gore-blood-burst-0": {
    "offset": 191.83575,
    "seconds": 0.65
  },
  "gore-blood-burst-1": {
    "offset": 192.52575,
    "seconds": 0.65
  },
  "gore-blood-burst-2": {
    "offset": 193.21575,
    "seconds": 0.65
  },
  "death-boss-iron-warden": {
    "offset": 193.90575,
    "seconds": 2.5
  },
  "death-boss-swarm-master": {
    "offset": 196.44575,
    "seconds": 2.5
  },
  "death-boss-putin": {
    "offset": 198.98575,
    "seconds": 2.5
  },
  "enemy-panic-0": {
    "offset": 201.52575,
    "seconds": 1.15
  },
  "enemy-panic-1": {
    "offset": 202.71575,
    "seconds": 1.15
  },
  "enemy-panic-2": {
    "offset": 203.90575,
    "seconds": 1.15
  },
  "enemy-panic-3": {
    "offset": 205.09575,
    "seconds": 1.15
  },
  "enemy-suspect-0": {
    "offset": 206.28575,
    "seconds": 0.95
  },
  "enemy-suspect-1": {
    "offset": 207.27575,
    "seconds": 0.95
  },
  "enemy-suspect-2": {
    "offset": 208.26575,
    "seconds": 0.95
  },
  "enemy-aggro-0": {
    "offset": 209.25575,
    "seconds": 1.1
  },
  "enemy-aggro-1": {
    "offset": 210.39575,
    "seconds": 1.1
  },
  "enemy-aggro-2": {
    "offset": 211.53575,
    "seconds": 1.1
  },
  "team-high-five": {
    "offset": 212.67575,
    "seconds": 1.05
  },
  "team-time-slow": {
    "offset": 213.76575,
    "seconds": 1.8
  },
  "team-hand-raise": {
    "offset": 215.60575,
    "seconds": 0.32
  },
  "team-hand-clap": {
    "offset": 215.96575,
    "seconds": 0.38
  },
  "team-hand-lower": {
    "offset": 216.38575,
    "seconds": 0.32
  },
  "usyk-punch": {
    "offset": 216.74575,
    "seconds": 1.0
  },
  "usyk-special": {
    "offset": 217.78575,
    "seconds": 1.0
  },
  "usyk-ultimate": {
    "offset": 218.82575,
    "seconds": 1.0
  },
  "almaziv-weapon": {
    "offset": 219.86575,
    "seconds": 1.0
  },
  "almaziv-special": {
    "offset": 220.90575,
    "seconds": 1.0
  },
  "almaziv-ultimate": {
    "offset": 221.94575,
    "seconds": 1.0
  },
  "klychko-weapon": {
    "offset": 222.98575,
    "seconds": 1.0
  },
  "klychko-special": {
    "offset": 224.02575,
    "seconds": 1.0
  },
  "taira-weapon": {
    "offset": 225.06575,
    "seconds": 1.0
  },
  "taira-special": {
    "offset": 226.10575,
    "seconds": 1.0
  },
  "taira-ultimate": {
    "offset": 227.14575,
    "seconds": 0.65
  },
  "prytula-weapon": {
    "offset": 227.83575,
    "seconds": 1.0
  },
  "prytula-special": {
    "offset": 228.87575,
    "seconds": 1.0
  },
  "prytula-ultimate": {
    "offset": 229.91575,
    "seconds": 1.0
  },
  "drone-lock": {
    "offset": 230.95575,
    "seconds": 0.7
  },
  "grenade-bounce": {
    "offset": 231.69575,
    "seconds": 0.3
  },
  "usyk-weapon-0": {
    "offset": 232.03575,
    "seconds": 0.33
  },
  "usyk-weapon-1": {
    "offset": 232.40575,
    "seconds": 0.33
  },
  "usyk-weapon-2": {
    "offset": 232.77575,
    "seconds": 0.33
  },
  "usyk-hit": {
    "offset": 233.14575,
    "seconds": 0.25
  },
  "usyk-special-end": {
    "offset": 233.43575,
    "seconds": 0.28
  },
  "usyk-ultimate-end": {
    "offset": 233.75575,
    "seconds": 0.28
  },
  "foley-usyk-step-0": {
    "offset": 234.07575,
    "seconds": 0.2
  },
  "foley-usyk-step-1": {
    "offset": 234.31575,
    "seconds": 0.2
  },
  "foley-usyk-step-2": {
    "offset": 234.55575,
    "seconds": 0.2
  },
  "foley-usyk-climb-0": {
    "offset": 234.79575,
    "seconds": 0.2
  },
  "foley-usyk-climb-1": {
    "offset": 235.03575,
    "seconds": 0.2
  },
  "foley-usyk-climb-2": {
    "offset": 235.27575,
    "seconds": 0.2
  },
  "foley-usyk-jump-0": {
    "offset": 235.51575,
    "seconds": 0.2
  },
  "foley-usyk-jump-1": {
    "offset": 235.75575,
    "seconds": 0.2
  },
  "foley-usyk-jump-2": {
    "offset": 235.99575,
    "seconds": 0.2
  },
  "foley-usyk-land-0": {
    "offset": 236.23575,
    "seconds": 0.26
  },
  "foley-usyk-land-1": {
    "offset": 236.53575,
    "seconds": 0.26
  },
  "foley-usyk-land-2": {
    "offset": 236.83575,
    "seconds": 0.26
  },
  "foley-usyk-hurt-0": {
    "offset": 237.13575,
    "seconds": 0.2
  },
  "foley-usyk-hurt-1": {
    "offset": 237.37575,
    "seconds": 0.2
  },
  "foley-usyk-hurt-2": {
    "offset": 237.61575,
    "seconds": 0.2
  },
  "foley-usyk-ready-0": {
    "offset": 237.85575,
    "seconds": 0.2
  },
  "foley-usyk-ready-1": {
    "offset": 238.09575,
    "seconds": 0.2
  },
  "foley-usyk-ready-2": {
    "offset": 238.33575,
    "seconds": 0.2
  },
  "almaziv-weapon-0": {
    "offset": 238.57575,
    "seconds": 0.5
  },
  "almaziv-weapon-1": {
    "offset": 239.11575,
    "seconds": 0.5
  },
  "almaziv-weapon-2": {
    "offset": 239.65575,
    "seconds": 0.5
  },
  "almaziv-hit": {
    "offset": 240.19575,
    "seconds": 0.25
  },
  "almaziv-special-end": {
    "offset": 240.48575,
    "seconds": 0.28
  },
  "almaziv-ultimate-end": {
    "offset": 240.80575,
    "seconds": 0.28
  },
  "almaziv-reload": {
    "offset": 241.12575,
    "seconds": 0.65
  },
  "almaziv-reload-end": {
    "offset": 241.81575,
    "seconds": 0.23
  },
  "foley-almaziv-step-0": {
    "offset": 242.08575,
    "seconds": 0.2
  },
  "foley-almaziv-step-1": {
    "offset": 242.32575,
    "seconds": 0.2
  },
  "foley-almaziv-step-2": {
    "offset": 242.56575,
    "seconds": 0.2
  },
  "foley-almaziv-climb-0": {
    "offset": 242.80575,
    "seconds": 0.2
  },
  "foley-almaziv-climb-1": {
    "offset": 243.04575,
    "seconds": 0.2
  },
  "foley-almaziv-climb-2": {
    "offset": 243.28575,
    "seconds": 0.2
  },
  "foley-almaziv-jump-0": {
    "offset": 243.52575,
    "seconds": 0.2
  },
  "foley-almaziv-jump-1": {
    "offset": 243.76575,
    "seconds": 0.2
  },
  "foley-almaziv-jump-2": {
    "offset": 244.00575,
    "seconds": 0.2
  },
  "foley-almaziv-land-0": {
    "offset": 244.24575,
    "seconds": 0.26
  },
  "foley-almaziv-land-1": {
    "offset": 244.54575,
    "seconds": 0.26
  },
  "foley-almaziv-land-2": {
    "offset": 244.84575,
    "seconds": 0.26
  },
  "foley-almaziv-hurt-0": {
    "offset": 245.14575,
    "seconds": 0.2
  },
  "foley-almaziv-hurt-1": {
    "offset": 245.38575,
    "seconds": 0.2
  },
  "foley-almaziv-hurt-2": {
    "offset": 245.62575,
    "seconds": 0.2
  },
  "foley-almaziv-ready-0": {
    "offset": 245.86575,
    "seconds": 0.2
  },
  "foley-almaziv-ready-1": {
    "offset": 246.10575,
    "seconds": 0.2
  },
  "foley-almaziv-ready-2": {
    "offset": 246.34575,
    "seconds": 0.2
  },
  "klychko-weapon-0": {
    "offset": 246.58575,
    "seconds": 0.33
  },
  "klychko-weapon-1": {
    "offset": 246.95575,
    "seconds": 0.33
  },
  "klychko-weapon-2": {
    "offset": 247.32575,
    "seconds": 0.33
  },
  "klychko-hit": {
    "offset": 247.69575,
    "seconds": 0.25
  },
  "klychko-ultimate": {
    "offset": 247.98575,
    "seconds": 1.2
  },
  "klychko-special-end": {
    "offset": 249.22575,
    "seconds": 0.28
  },
  "klychko-ultimate-end": {
    "offset": 249.54575,
    "seconds": 0.28
  },
  "foley-klychko-step-0": {
    "offset": 249.86575,
    "seconds": 0.2
  },
  "foley-klychko-step-1": {
    "offset": 250.10575,
    "seconds": 0.2
  },
  "foley-klychko-step-2": {
    "offset": 250.34575,
    "seconds": 0.2
  },
  "foley-klychko-climb-0": {
    "offset": 250.58575,
    "seconds": 0.2
  },
  "foley-klychko-climb-1": {
    "offset": 250.82575,
    "seconds": 0.2
  },
  "foley-klychko-climb-2": {
    "offset": 251.06575,
    "seconds": 0.2
  },
  "foley-klychko-jump-0": {
    "offset": 251.30575,
    "seconds": 0.2
  },
  "foley-klychko-jump-1": {
    "offset": 251.54575,
    "seconds": 0.2
  },
  "foley-klychko-jump-2": {
    "offset": 251.78575,
    "seconds": 0.2
  },
  "foley-klychko-land-0": {
    "offset": 252.02575,
    "seconds": 0.26
  },
  "foley-klychko-land-1": {
    "offset": 252.32575,
    "seconds": 0.26
  },
  "foley-klychko-land-2": {
    "offset": 252.62575,
    "seconds": 0.26
  },
  "foley-klychko-hurt-0": {
    "offset": 252.92575,
    "seconds": 0.2
  },
  "foley-klychko-hurt-1": {
    "offset": 253.16575,
    "seconds": 0.2
  },
  "foley-klychko-hurt-2": {
    "offset": 253.40575,
    "seconds": 0.2
  },
  "foley-klychko-ready-0": {
    "offset": 253.64575,
    "seconds": 0.2
  },
  "foley-klychko-ready-1": {
    "offset": 253.88575,
    "seconds": 0.2
  },
  "foley-klychko-ready-2": {
    "offset": 254.12575,
    "seconds": 0.2
  },
  "taira-weapon-0": {
    "offset": 254.36575,
    "seconds": 0.33
  },
  "taira-weapon-1": {
    "offset": 254.73575,
    "seconds": 0.33
  },
  "taira-weapon-2": {
    "offset": 255.10575,
    "seconds": 0.33
  },
  "taira-hit": {
    "offset": 255.47575,
    "seconds": 0.25
  },
  "taira-special-end": {
    "offset": 255.76575,
    "seconds": 0.28
  },
  "taira-ultimate-end": {
    "offset": 256.08575,
    "seconds": 0.28
  },
  "foley-taira-step-0": {
    "offset": 256.40575,
    "seconds": 0.2
  },
  "foley-taira-step-1": {
    "offset": 256.64575,
    "seconds": 0.2
  },
  "foley-taira-step-2": {
    "offset": 256.88575,
    "seconds": 0.2
  },
  "foley-taira-climb-0": {
    "offset": 257.12575,
    "seconds": 0.2
  },
  "foley-taira-climb-1": {
    "offset": 257.36575,
    "seconds": 0.2
  },
  "foley-taira-climb-2": {
    "offset": 257.60575,
    "seconds": 0.2
  },
  "foley-taira-jump-0": {
    "offset": 257.84575,
    "seconds": 0.2
  },
  "foley-taira-jump-1": {
    "offset": 258.08575,
    "seconds": 0.2
  },
  "foley-taira-jump-2": {
    "offset": 258.32575,
    "seconds": 0.2
  },
  "foley-taira-land-0": {
    "offset": 258.56575,
    "seconds": 0.26
  },
  "foley-taira-land-1": {
    "offset": 258.86575,
    "seconds": 0.26
  },
  "foley-taira-land-2": {
    "offset": 259.16575,
    "seconds": 0.26
  },
  "foley-taira-hurt-0": {
    "offset": 259.46575,
    "seconds": 0.2
  },
  "foley-taira-hurt-1": {
    "offset": 259.70575,
    "seconds": 0.2
  },
  "foley-taira-hurt-2": {
    "offset": 259.94575,
    "seconds": 0.2
  },
  "foley-taira-ready-0": {
    "offset": 260.18575,
    "seconds": 0.2
  },
  "foley-taira-ready-1": {
    "offset": 260.42575,
    "seconds": 0.2
  },
  "foley-taira-ready-2": {
    "offset": 260.66575,
    "seconds": 0.2
  },
  "prytula-weapon-0": {
    "offset": 260.90575,
    "seconds": 0.33
  },
  "prytula-weapon-1": {
    "offset": 261.27575,
    "seconds": 0.33
  },
  "prytula-weapon-2": {
    "offset": 261.64575,
    "seconds": 0.33
  },
  "prytula-hit": {
    "offset": 262.01575,
    "seconds": 0.25
  },
  "prytula-special-end": {
    "offset": 262.30575,
    "seconds": 0.28
  },
  "prytula-ultimate-end": {
    "offset": 262.62575,
    "seconds": 0.28
  },
  "prytula-reload": {
    "offset": 262.94575,
    "seconds": 0.65
  },
  "prytula-reload-end": {
    "offset": 263.63575,
    "seconds": 0.23
  },
  "foley-prytula-step-0": {
    "offset": 263.90575,
    "seconds": 0.2
  },
  "foley-prytula-step-1": {
    "offset": 264.14575,
    "seconds": 0.2
  },
  "foley-prytula-step-2": {
    "offset": 264.38575,
    "seconds": 0.2
  },
  "foley-prytula-climb-0": {
    "offset": 264.62575,
    "seconds": 0.2
  },
  "foley-prytula-climb-1": {
    "offset": 264.86575,
    "seconds": 0.2
  },
  "foley-prytula-climb-2": {
    "offset": 265.10575,
    "seconds": 0.2
  },
  "foley-prytula-jump-0": {
    "offset": 265.34575,
    "seconds": 0.2
  },
  "foley-prytula-jump-1": {
    "offset": 265.58575,
    "seconds": 0.2
  },
  "foley-prytula-jump-2": {
    "offset": 265.82575,
    "seconds": 0.2
  },
  "foley-prytula-land-0": {
    "offset": 266.06575,
    "seconds": 0.26
  },
  "foley-prytula-land-1": {
    "offset": 266.36575,
    "seconds": 0.26
  },
  "foley-prytula-land-2": {
    "offset": 266.66575,
    "seconds": 0.26
  },
  "foley-prytula-hurt-0": {
    "offset": 266.96575,
    "seconds": 0.2
  },
  "foley-prytula-hurt-1": {
    "offset": 267.20575,
    "seconds": 0.2
  },
  "foley-prytula-hurt-2": {
    "offset": 267.44575,
    "seconds": 0.2
  },
  "foley-prytula-ready-0": {
    "offset": 267.68575,
    "seconds": 0.2
  },
  "foley-prytula-ready-1": {
    "offset": 267.92575,
    "seconds": 0.2
  },
  "foley-prytula-ready-2": {
    "offset": 268.16575,
    "seconds": 0.2
  },
  "klychko-charge-v3": {
    "offset": 268.40575,
    "seconds": 0.65
  },
  "klychko-uppercut-v2": {
    "offset": 269.09575,
    "seconds": 0.7
  },
  "klychko-slam-v2": {
    "offset": 269.83575,
    "seconds": 1.1
  },
  "klychko-gather-v5": {
    "offset": 270.97575,
    "seconds": 0.85
  },
  "klychko-ready-v4": {
    "offset": 271.86575,
    "seconds": 0.3
  },
  "taira-field-v2": {
    "offset": 272.20575,
    "seconds": 0.7
  }
} as const;
export type SfxId=keyof typeof SFX_ASSETS;
