// Generated by tools/build-combat-sfx.py; provenance: docs/COMBAT_SFX_ASSETS.json.
export const SFX_BANK = "/assets/audio/sfx/combat-bank.wav";
export const SFX_ASSETS = {
  "shevchenko-weapon-0": {
    "offset": 0.0,
    "seconds": 0.415875
  },
  "shevchenko-weapon-1": {
    "offset": 0.455875,
    "seconds": 0.40570833333333334
  },
  "shevchenko-weapon-2": {
    "offset": 0.9015833333333333,
    "seconds": 0.39608333333333334
  },
  "lesya-weapon-0": {
    "offset": 1.3376666666666666,
    "seconds": 0.3617916666666667
  },
  "lesya-weapon-1": {
    "offset": 1.7394583333333333,
    "seconds": 0.3529583333333333
  },
  "lesya-weapon-2": {
    "offset": 2.132416666666667,
    "seconds": 0.344625
  },
  "franko-weapon-0": {
    "offset": 2.5170416666666666,
    "seconds": 0.12883333333333333
  },
  "franko-weapon-1": {
    "offset": 2.685875,
    "seconds": 0.12583333333333332
  },
  "franko-weapon-2": {
    "offset": 2.8517083333333333,
    "seconds": 0.12304166666666666
  },
  "bandera-weapon-0": {
    "offset": 3.01475,
    "seconds": 0.174125
  },
  "bandera-weapon-1": {
    "offset": 3.228875,
    "seconds": 0.17
  },
  "bandera-weapon-2": {
    "offset": 3.438875,
    "seconds": 0.166125
  },
  "mamai-weapon-0": {
    "offset": 3.645,
    "seconds": 0.5485
  },
  "mamai-weapon-1": {
    "offset": 4.2335,
    "seconds": 0.535
  },
  "mamai-weapon-2": {
    "offset": 4.8085,
    "seconds": 0.5222083333333334
  },
  "mamai-melee-weapon-0": {
    "offset": 5.370708333333333,
    "seconds": 0.25616666666666665
  },
  "mamai-melee-weapon-1": {
    "offset": 5.666875,
    "seconds": 0.25
  },
  "mamai-melee-weapon-2": {
    "offset": 5.956875,
    "seconds": 0.24416666666666667
  },
  "bayraktar-weapon-0": {
    "offset": 6.241041666666667,
    "seconds": 0.3617916666666667
  },
  "bayraktar-weapon-1": {
    "offset": 6.642833333333333,
    "seconds": 0.3529583333333333
  },
  "bayraktar-weapon-2": {
    "offset": 7.035791666666666,
    "seconds": 0.344625
  },
  "ghost-weapon-0": {
    "offset": 7.420416666666667,
    "seconds": 0.24591666666666667
  },
  "ghost-weapon-1": {
    "offset": 7.706333333333333,
    "seconds": 0.24
  },
  "ghost-weapon-2": {
    "offset": 7.9863333333333335,
    "seconds": 0.23441666666666666
  },
  "zelensky-weapon-0": {
    "offset": 8.26075,
    "seconds": 0.3177083333333333
  },
  "zelensky-weapon-1": {
    "offset": 8.618458333333333,
    "seconds": 0.31
  },
  "zelensky-weapon-2": {
    "offset": 8.968458333333333,
    "seconds": 0.30270833333333336
  },
  "bilozerska-weapon-0": {
    "offset": 9.311166666666667,
    "seconds": 0.8818333333333334
  },
  "bilozerska-weapon-1": {
    "offset": 10.233,
    "seconds": 0.86
  },
  "bilozerska-weapon-2": {
    "offset": 11.133,
    "seconds": 0.8392916666666667
  },
  "it-army-weapon-0": {
    "offset": 12.012291666666666,
    "seconds": 0.3177083333333333
  },
  "it-army-weapon-1": {
    "offset": 12.37,
    "seconds": 0.31
  },
  "it-army-weapon-2": {
    "offset": 12.72,
    "seconds": 0.30270833333333336
  },
  "skovoroda-weapon-0": {
    "offset": 13.062708333333333,
    "seconds": 0.06954166666666667
  },
  "skovoroda-weapon-1": {
    "offset": 13.17225,
    "seconds": 0.06804166666666667
  },
  "skovoroda-weapon-2": {
    "offset": 13.280291666666667,
    "seconds": 0.06666666666666667
  },
  "shevchenko-hit": {
    "offset": 13.386958333333334,
    "seconds": 0.42
  },
  "lesya-hit": {
    "offset": 13.846958333333333,
    "seconds": 0.42
  },
  "franko-hit": {
    "offset": 14.306958333333334,
    "seconds": 0.42
  },
  "bandera-hit": {
    "offset": 14.766958333333333,
    "seconds": 0.42
  },
  "mamai-hit": {
    "offset": 15.226958333333334,
    "seconds": 0.42
  },
  "bayraktar-hit": {
    "offset": 15.686958333333333,
    "seconds": 0.42
  },
  "ghost-hit": {
    "offset": 16.146958333333334,
    "seconds": 0.42
  },
  "zelensky-hit": {
    "offset": 16.606958333333335,
    "seconds": 0.42
  },
  "bilozerska-hit": {
    "offset": 17.066958333333332,
    "seconds": 0.42
  },
  "it-army-hit": {
    "offset": 17.526958333333333,
    "seconds": 0.42
  },
  "skovoroda-hit": {
    "offset": 17.986958333333334,
    "seconds": 0.42
  },
  "ricochet": {
    "offset": 18.446958333333335,
    "seconds": 0.45
  },
  "explosion": {
    "offset": 18.936958333333333,
    "seconds": 1.3
  },
  "glass-fire": {
    "offset": 20.276958333333333,
    "seconds": 0.65
  },
  "roots": {
    "offset": 20.966958333333334,
    "seconds": 0.7
  },
  "stone-hit": {
    "offset": 21.706958333333333,
    "seconds": 0.5
  },
  "thunder": {
    "offset": 22.246958333333332,
    "seconds": 1.3
  },
  "rail-shot": {
    "offset": 23.58695833333333,
    "seconds": 1.1
  },
  "bolt": {
    "offset": 24.726958333333332,
    "seconds": 0.4
  },
  "mine-arm": {
    "offset": 25.166958333333334,
    "seconds": 0.22
  },
  "rocket": {
    "offset": 25.426958333333335,
    "seconds": 0.65
  },
  "shevchenko-special": {
    "offset": 26.116958333333333,
    "seconds": 1.7
  },
  "lesya-special": {
    "offset": 27.856958333333335,
    "seconds": 0.554
  },
  "lesya-ultimate": {
    "offset": 28.450958333333332,
    "seconds": 0.71
  },
  "franko-special": {
    "offset": 29.200958333333332,
    "seconds": 0.5923333333333334
  },
  "franko-ultimate": {
    "offset": 29.833291666666668,
    "seconds": 0.985
  },
  "bandera-special": {
    "offset": 30.858291666666666,
    "seconds": 0.332875
  },
  "bandera-ultimate": {
    "offset": 31.231166666666667,
    "seconds": 1.31
  },
  "mamai-special": {
    "offset": 32.58116666666667,
    "seconds": 0.17
  },
  "mamai-ultimate": {
    "offset": 32.79116666666667,
    "seconds": 1.01
  },
  "bayraktar-special": {
    "offset": 33.841166666666666,
    "seconds": 0.51
  },
  "bayraktar-ultimate": {
    "offset": 34.39116666666666,
    "seconds": 0.9433333333333334
  },
  "ghost-special": {
    "offset": 35.3745,
    "seconds": 0.51
  },
  "ghost-ultimate": {
    "offset": 35.9245,
    "seconds": 1.8282083333333334
  },
  "zelensky-special": {
    "offset": 37.79270833333333,
    "seconds": 0.21591666666666667
  },
  "zelensky-ultimate": {
    "offset": 38.048625,
    "seconds": 0.4217916666666667
  },
  "bilozerska-special": {
    "offset": 38.510416666666664,
    "seconds": 0.27241666666666664
  },
  "bilozerska-ultimate": {
    "offset": 38.822833333333335,
    "seconds": 0.51
  },
  "it-army-special": {
    "offset": 39.37283333333333,
    "seconds": 0.26
  },
  "it-army-ultimate": {
    "offset": 39.67283333333334,
    "seconds": 1.0933333333333333
  },
  "skovoroda-special": {
    "offset": 40.80616666666667,
    "seconds": 0.48570833333333335
  },
  "skovoroda-ultimate": {
    "offset": 41.331875,
    "seconds": 0.71
  },
  "shevchenko-ultimate": {
    "offset": 42.081875,
    "seconds": 0.6
  },
  "lesya-special-loop": {
    "offset": 42.721875,
    "seconds": 1.75
  },
  "lesya-ultimate-loop": {
    "offset": 44.511875,
    "seconds": 1.75
  },
  "franko-special-loop": {
    "offset": 46.301875,
    "seconds": 1.75
  },
  "bandera-special-loop": {
    "offset": 48.091875,
    "seconds": 1.75
  },
  "bandera-ultimate-loop": {
    "offset": 49.881875,
    "seconds": 1.75
  },
  "mamai-special-loop": {
    "offset": 51.671875,
    "seconds": 0.95
  },
  "mamai-ultimate-loop": {
    "offset": 52.661875,
    "seconds": 0.95
  },
  "bayraktar-special-loop": {
    "offset": 53.651875,
    "seconds": 1.75
  },
  "bayraktar-ultimate-loop": {
    "offset": 55.441875,
    "seconds": 1.75
  },
  "ghost-ultimate-loop": {
    "offset": 57.231875,
    "seconds": 1.75
  },
  "zelensky-ultimate-loop": {
    "offset": 59.021875,
    "seconds": 1.75
  },
  "it-army-ultimate-loop": {
    "offset": 60.811875,
    "seconds": 1.75
  },
  "skovoroda-special-loop": {
    "offset": 62.601875,
    "seconds": 1.75
  },
  "skovoroda-ultimate-loop": {
    "offset": 64.391875,
    "seconds": 1.75
  },
  "shevchenko-special-end": {
    "offset": 66.181875,
    "seconds": 0.5
  },
  "shevchenko-ultimate-end": {
    "offset": 66.721875,
    "seconds": 0.5
  },
  "lesya-special-end": {
    "offset": 67.261875,
    "seconds": 0.5
  },
  "lesya-ultimate-end": {
    "offset": 67.801875,
    "seconds": 0.5
  },
  "franko-special-end": {
    "offset": 68.341875,
    "seconds": 0.5
  },
  "franko-ultimate-end": {
    "offset": 68.881875,
    "seconds": 0.5
  },
  "bandera-special-end": {
    "offset": 69.421875,
    "seconds": 0.5
  },
  "bandera-ultimate-end": {
    "offset": 69.961875,
    "seconds": 0.5
  },
  "mamai-special-end": {
    "offset": 70.501875,
    "seconds": 0.5
  },
  "mamai-ultimate-end": {
    "offset": 71.041875,
    "seconds": 0.5
  },
  "bayraktar-special-end": {
    "offset": 71.581875,
    "seconds": 0.5
  },
  "bayraktar-ultimate-end": {
    "offset": 72.121875,
    "seconds": 0.5
  },
  "ghost-special-end": {
    "offset": 72.661875,
    "seconds": 0.5
  },
  "ghost-ultimate-end": {
    "offset": 73.201875,
    "seconds": 0.5
  },
  "zelensky-special-end": {
    "offset": 73.741875,
    "seconds": 0.5
  },
  "zelensky-ultimate-end": {
    "offset": 74.281875,
    "seconds": 0.5
  },
  "bilozerska-special-end": {
    "offset": 74.821875,
    "seconds": 0.5
  },
  "bilozerska-ultimate-end": {
    "offset": 75.361875,
    "seconds": 0.5
  },
  "it-army-special-end": {
    "offset": 75.901875,
    "seconds": 0.5
  },
  "it-army-ultimate-end": {
    "offset": 76.441875,
    "seconds": 0.5
  },
  "skovoroda-special-end": {
    "offset": 76.981875,
    "seconds": 0.5
  },
  "skovoroda-ultimate-end": {
    "offset": 77.521875,
    "seconds": 0.5
  },
  "lesya-reload": {
    "offset": 78.061875,
    "seconds": 1.2799583333333333
  },
  "lesya-reload-end": {
    "offset": 79.38183333333333,
    "seconds": 0.2
  },
  "bandera-reload": {
    "offset": 79.62183333333333,
    "seconds": 2.2799583333333335
  },
  "bandera-reload-end": {
    "offset": 81.94179166666666,
    "seconds": 0.2
  },
  "mamai-reload": {
    "offset": 82.18179166666667,
    "seconds": 2.6799583333333334
  },
  "mamai-reload-end": {
    "offset": 84.90175,
    "seconds": 0.2
  },
  "bayraktar-reload": {
    "offset": 85.14175,
    "seconds": 2.88
  },
  "bayraktar-reload-end": {
    "offset": 88.06175,
    "seconds": 0.2
  },
  "ghost-reload": {
    "offset": 88.30175,
    "seconds": 1.98
  },
  "ghost-reload-end": {
    "offset": 90.32175,
    "seconds": 0.2
  },
  "zelensky-reload": {
    "offset": 90.56175,
    "seconds": 1.68
  },
  "zelensky-reload-end": {
    "offset": 92.28175,
    "seconds": 0.2
  },
  "bilozerska-reload": {
    "offset": 92.52175,
    "seconds": 4.68
  },
  "bilozerska-reload-end": {
    "offset": 97.24175,
    "seconds": 0.2
  },
  "it-army-reload": {
    "offset": 97.48175,
    "seconds": 1.88
  },
  "it-army-reload-end": {
    "offset": 99.40175,
    "seconds": 0.2
  },
  "support-infantry": {
    "offset": 99.64175,
    "seconds": 0.21
  },
  "support-turret": {
    "offset": 99.89175,
    "seconds": 0.23
  },
  "turret-step": {
    "offset": 100.16175,
    "seconds": 0.3529583333333333
  },
  "follower-hurt": {
    "offset": 100.55470833333334,
    "seconds": 0.22908333333333333
  },
  "follower-down": {
    "offset": 100.82379166666666,
    "seconds": 0.27241666666666664
  },
  "barrel-lift": {
    "offset": 101.13620833333333,
    "seconds": 0.6039583333333334
  },
  "barrel-throw": {
    "offset": 101.78016666666667,
    "seconds": 0.17
  },
  "armor-hit": {
    "offset": 101.99016666666667,
    "seconds": 0.08679166666666667
  },
  "tank-land": {
    "offset": 102.11695833333333,
    "seconds": 0.289875
  },
  "tank-jump": {
    "offset": 102.44683333333333,
    "seconds": 0.5814583333333333
  },
  "hatch": {
    "offset": 103.06829166666667,
    "seconds": 0.39591666666666664
  },
  "tank-shot": {
    "offset": 103.50420833333334,
    "seconds": 1.2407916666666667
  },
  "tank-engine": {
    "offset": 104.785,
    "seconds": 2.51
  },
  "plane-engine": {
    "offset": 107.335,
    "seconds": 1.8282083333333334
  },
  "drone-engine": {
    "offset": 109.20320833333334,
    "seconds": 0.75075
  },
  "drone-dive": {
    "offset": 109.99395833333334,
    "seconds": 0.61
  },
  "enemy-alert": {
    "offset": 110.64395833333333,
    "seconds": 0.15708333333333332
  },
  "enemy-fuse": {
    "offset": 110.84104166666667,
    "seconds": 0.7529583333333333
  },
  "pickup": {
    "offset": 111.634,
    "seconds": 0.207625
  },
  "debris": {
    "offset": 111.881625,
    "seconds": 0.289875
  },
  "foley-shevchenko-step-0": {
    "offset": 112.2115,
    "seconds": 0.2
  },
  "foley-shevchenko-step-1": {
    "offset": 112.4515,
    "seconds": 0.2
  },
  "foley-shevchenko-step-2": {
    "offset": 112.6915,
    "seconds": 0.2
  },
  "foley-shevchenko-climb-0": {
    "offset": 112.9315,
    "seconds": 0.2
  },
  "foley-shevchenko-climb-1": {
    "offset": 113.1715,
    "seconds": 0.2
  },
  "foley-shevchenko-climb-2": {
    "offset": 113.4115,
    "seconds": 0.2
  },
  "foley-shevchenko-jump-0": {
    "offset": 113.6515,
    "seconds": 0.2
  },
  "foley-shevchenko-jump-1": {
    "offset": 113.8915,
    "seconds": 0.2
  },
  "foley-shevchenko-jump-2": {
    "offset": 114.1315,
    "seconds": 0.2
  },
  "foley-shevchenko-land-0": {
    "offset": 114.3715,
    "seconds": 0.26
  },
  "foley-shevchenko-land-1": {
    "offset": 114.6715,
    "seconds": 0.26
  },
  "foley-shevchenko-land-2": {
    "offset": 114.9715,
    "seconds": 0.26
  },
  "foley-shevchenko-hurt-0": {
    "offset": 115.2715,
    "seconds": 0.2
  },
  "foley-shevchenko-hurt-1": {
    "offset": 115.5115,
    "seconds": 0.2
  },
  "foley-shevchenko-hurt-2": {
    "offset": 115.7515,
    "seconds": 0.2
  },
  "foley-shevchenko-ready-0": {
    "offset": 115.9915,
    "seconds": 0.2
  },
  "foley-shevchenko-ready-1": {
    "offset": 116.2315,
    "seconds": 0.2
  },
  "foley-shevchenko-ready-2": {
    "offset": 116.4715,
    "seconds": 0.2
  },
  "foley-lesya-step-0": {
    "offset": 116.7115,
    "seconds": 0.2
  },
  "foley-lesya-step-1": {
    "offset": 116.9515,
    "seconds": 0.2
  },
  "foley-lesya-step-2": {
    "offset": 117.1915,
    "seconds": 0.2
  },
  "foley-lesya-climb-0": {
    "offset": 117.4315,
    "seconds": 0.2
  },
  "foley-lesya-climb-1": {
    "offset": 117.6715,
    "seconds": 0.2
  },
  "foley-lesya-climb-2": {
    "offset": 117.9115,
    "seconds": 0.2
  },
  "foley-lesya-jump-0": {
    "offset": 118.1515,
    "seconds": 0.2
  },
  "foley-lesya-jump-1": {
    "offset": 118.3915,
    "seconds": 0.2
  },
  "foley-lesya-jump-2": {
    "offset": 118.6315,
    "seconds": 0.2
  },
  "foley-lesya-land-0": {
    "offset": 118.8715,
    "seconds": 0.26
  },
  "foley-lesya-land-1": {
    "offset": 119.1715,
    "seconds": 0.26
  },
  "foley-lesya-land-2": {
    "offset": 119.4715,
    "seconds": 0.26
  },
  "foley-lesya-hurt-0": {
    "offset": 119.7715,
    "seconds": 0.2
  },
  "foley-lesya-hurt-1": {
    "offset": 120.0115,
    "seconds": 0.2
  },
  "foley-lesya-hurt-2": {
    "offset": 120.2515,
    "seconds": 0.2
  },
  "foley-lesya-ready-0": {
    "offset": 120.4915,
    "seconds": 0.2
  },
  "foley-lesya-ready-1": {
    "offset": 120.7315,
    "seconds": 0.2
  },
  "foley-lesya-ready-2": {
    "offset": 120.9715,
    "seconds": 0.2
  },
  "foley-franko-step-0": {
    "offset": 121.2115,
    "seconds": 0.2
  },
  "foley-franko-step-1": {
    "offset": 121.4515,
    "seconds": 0.2
  },
  "foley-franko-step-2": {
    "offset": 121.6915,
    "seconds": 0.2
  },
  "foley-franko-climb-0": {
    "offset": 121.9315,
    "seconds": 0.2
  },
  "foley-franko-climb-1": {
    "offset": 122.1715,
    "seconds": 0.2
  },
  "foley-franko-climb-2": {
    "offset": 122.4115,
    "seconds": 0.2
  },
  "foley-franko-jump-0": {
    "offset": 122.6515,
    "seconds": 0.2
  },
  "foley-franko-jump-1": {
    "offset": 122.8915,
    "seconds": 0.2
  },
  "foley-franko-jump-2": {
    "offset": 123.1315,
    "seconds": 0.2
  },
  "foley-franko-land-0": {
    "offset": 123.3715,
    "seconds": 0.26
  },
  "foley-franko-land-1": {
    "offset": 123.6715,
    "seconds": 0.26
  },
  "foley-franko-land-2": {
    "offset": 123.9715,
    "seconds": 0.26
  },
  "foley-franko-hurt-0": {
    "offset": 124.2715,
    "seconds": 0.2
  },
  "foley-franko-hurt-1": {
    "offset": 124.5115,
    "seconds": 0.2
  },
  "foley-franko-hurt-2": {
    "offset": 124.7515,
    "seconds": 0.2
  },
  "foley-franko-ready-0": {
    "offset": 124.9915,
    "seconds": 0.2
  },
  "foley-franko-ready-1": {
    "offset": 125.2315,
    "seconds": 0.2
  },
  "foley-franko-ready-2": {
    "offset": 125.4715,
    "seconds": 0.2
  },
  "foley-bandera-step-0": {
    "offset": 125.7115,
    "seconds": 0.2
  },
  "foley-bandera-step-1": {
    "offset": 125.9515,
    "seconds": 0.2
  },
  "foley-bandera-step-2": {
    "offset": 126.1915,
    "seconds": 0.2
  },
  "foley-bandera-climb-0": {
    "offset": 126.4315,
    "seconds": 0.2
  },
  "foley-bandera-climb-1": {
    "offset": 126.6715,
    "seconds": 0.2
  },
  "foley-bandera-climb-2": {
    "offset": 126.9115,
    "seconds": 0.2
  },
  "foley-bandera-jump-0": {
    "offset": 127.1515,
    "seconds": 0.2
  },
  "foley-bandera-jump-1": {
    "offset": 127.3915,
    "seconds": 0.2
  },
  "foley-bandera-jump-2": {
    "offset": 127.6315,
    "seconds": 0.2
  },
  "foley-bandera-land-0": {
    "offset": 127.8715,
    "seconds": 0.26
  },
  "foley-bandera-land-1": {
    "offset": 128.1715,
    "seconds": 0.26
  },
  "foley-bandera-land-2": {
    "offset": 128.4715,
    "seconds": 0.26
  },
  "foley-bandera-hurt-0": {
    "offset": 128.7715,
    "seconds": 0.2
  },
  "foley-bandera-hurt-1": {
    "offset": 129.0115,
    "seconds": 0.2
  },
  "foley-bandera-hurt-2": {
    "offset": 129.2515,
    "seconds": 0.2
  },
  "foley-bandera-ready-0": {
    "offset": 129.4915,
    "seconds": 0.2
  },
  "foley-bandera-ready-1": {
    "offset": 129.7315,
    "seconds": 0.2
  },
  "foley-bandera-ready-2": {
    "offset": 129.9715,
    "seconds": 0.2
  },
  "foley-mamai-step-0": {
    "offset": 130.2115,
    "seconds": 0.2
  },
  "foley-mamai-step-1": {
    "offset": 130.4515,
    "seconds": 0.2
  },
  "foley-mamai-step-2": {
    "offset": 130.6915,
    "seconds": 0.2
  },
  "foley-mamai-climb-0": {
    "offset": 130.9315,
    "seconds": 0.2
  },
  "foley-mamai-climb-1": {
    "offset": 131.1715,
    "seconds": 0.2
  },
  "foley-mamai-climb-2": {
    "offset": 131.4115,
    "seconds": 0.2
  },
  "foley-mamai-jump-0": {
    "offset": 131.6515,
    "seconds": 0.2
  },
  "foley-mamai-jump-1": {
    "offset": 131.8915,
    "seconds": 0.2
  },
  "foley-mamai-jump-2": {
    "offset": 132.1315,
    "seconds": 0.2
  },
  "foley-mamai-land-0": {
    "offset": 132.3715,
    "seconds": 0.26
  },
  "foley-mamai-land-1": {
    "offset": 132.6715,
    "seconds": 0.26
  },
  "foley-mamai-land-2": {
    "offset": 132.9715,
    "seconds": 0.26
  },
  "foley-mamai-hurt-0": {
    "offset": 133.2715,
    "seconds": 0.2
  },
  "foley-mamai-hurt-1": {
    "offset": 133.5115,
    "seconds": 0.2
  },
  "foley-mamai-hurt-2": {
    "offset": 133.7515,
    "seconds": 0.2
  },
  "foley-mamai-ready-0": {
    "offset": 133.9915,
    "seconds": 0.2
  },
  "foley-mamai-ready-1": {
    "offset": 134.2315,
    "seconds": 0.2
  },
  "foley-mamai-ready-2": {
    "offset": 134.4715,
    "seconds": 0.2
  },
  "foley-bayraktar-step-0": {
    "offset": 134.7115,
    "seconds": 0.2
  },
  "foley-bayraktar-step-1": {
    "offset": 134.9515,
    "seconds": 0.2
  },
  "foley-bayraktar-step-2": {
    "offset": 135.1915,
    "seconds": 0.2
  },
  "foley-bayraktar-climb-0": {
    "offset": 135.4315,
    "seconds": 0.2
  },
  "foley-bayraktar-climb-1": {
    "offset": 135.6715,
    "seconds": 0.2
  },
  "foley-bayraktar-climb-2": {
    "offset": 135.9115,
    "seconds": 0.2
  },
  "foley-bayraktar-jump-0": {
    "offset": 136.1515,
    "seconds": 0.2
  },
  "foley-bayraktar-jump-1": {
    "offset": 136.3915,
    "seconds": 0.2
  },
  "foley-bayraktar-jump-2": {
    "offset": 136.6315,
    "seconds": 0.2
  },
  "foley-bayraktar-land-0": {
    "offset": 136.8715,
    "seconds": 0.26
  },
  "foley-bayraktar-land-1": {
    "offset": 137.1715,
    "seconds": 0.26
  },
  "foley-bayraktar-land-2": {
    "offset": 137.4715,
    "seconds": 0.26
  },
  "foley-bayraktar-hurt-0": {
    "offset": 137.7715,
    "seconds": 0.2
  },
  "foley-bayraktar-hurt-1": {
    "offset": 138.0115,
    "seconds": 0.2
  },
  "foley-bayraktar-hurt-2": {
    "offset": 138.2515,
    "seconds": 0.2
  },
  "foley-bayraktar-ready-0": {
    "offset": 138.4915,
    "seconds": 0.2
  },
  "foley-bayraktar-ready-1": {
    "offset": 138.7315,
    "seconds": 0.2
  },
  "foley-bayraktar-ready-2": {
    "offset": 138.9715,
    "seconds": 0.2
  },
  "foley-ghost-step-0": {
    "offset": 139.2115,
    "seconds": 0.2
  },
  "foley-ghost-step-1": {
    "offset": 139.4515,
    "seconds": 0.2
  },
  "foley-ghost-step-2": {
    "offset": 139.6915,
    "seconds": 0.2
  },
  "foley-ghost-climb-0": {
    "offset": 139.9315,
    "seconds": 0.2
  },
  "foley-ghost-climb-1": {
    "offset": 140.1715,
    "seconds": 0.2
  },
  "foley-ghost-climb-2": {
    "offset": 140.4115,
    "seconds": 0.2
  },
  "foley-ghost-jump-0": {
    "offset": 140.6515,
    "seconds": 0.2
  },
  "foley-ghost-jump-1": {
    "offset": 140.8915,
    "seconds": 0.2
  },
  "foley-ghost-jump-2": {
    "offset": 141.1315,
    "seconds": 0.2
  },
  "foley-ghost-land-0": {
    "offset": 141.3715,
    "seconds": 0.26
  },
  "foley-ghost-land-1": {
    "offset": 141.6715,
    "seconds": 0.26
  },
  "foley-ghost-land-2": {
    "offset": 141.9715,
    "seconds": 0.26
  },
  "foley-ghost-hurt-0": {
    "offset": 142.2715,
    "seconds": 0.2
  },
  "foley-ghost-hurt-1": {
    "offset": 142.5115,
    "seconds": 0.2
  },
  "foley-ghost-hurt-2": {
    "offset": 142.7515,
    "seconds": 0.2
  },
  "foley-ghost-ready-0": {
    "offset": 142.9915,
    "seconds": 0.2
  },
  "foley-ghost-ready-1": {
    "offset": 143.2315,
    "seconds": 0.2
  },
  "foley-ghost-ready-2": {
    "offset": 143.4715,
    "seconds": 0.2
  },
  "foley-zelensky-step-0": {
    "offset": 143.7115,
    "seconds": 0.2
  },
  "foley-zelensky-step-1": {
    "offset": 143.9515,
    "seconds": 0.2
  },
  "foley-zelensky-step-2": {
    "offset": 144.1915,
    "seconds": 0.2
  },
  "foley-zelensky-climb-0": {
    "offset": 144.4315,
    "seconds": 0.2
  },
  "foley-zelensky-climb-1": {
    "offset": 144.6715,
    "seconds": 0.2
  },
  "foley-zelensky-climb-2": {
    "offset": 144.9115,
    "seconds": 0.2
  },
  "foley-zelensky-jump-0": {
    "offset": 145.1515,
    "seconds": 0.2
  },
  "foley-zelensky-jump-1": {
    "offset": 145.3915,
    "seconds": 0.2
  },
  "foley-zelensky-jump-2": {
    "offset": 145.6315,
    "seconds": 0.2
  },
  "foley-zelensky-land-0": {
    "offset": 145.8715,
    "seconds": 0.26
  },
  "foley-zelensky-land-1": {
    "offset": 146.1715,
    "seconds": 0.26
  },
  "foley-zelensky-land-2": {
    "offset": 146.4715,
    "seconds": 0.26
  },
  "foley-zelensky-hurt-0": {
    "offset": 146.7715,
    "seconds": 0.2
  },
  "foley-zelensky-hurt-1": {
    "offset": 147.0115,
    "seconds": 0.2
  },
  "foley-zelensky-hurt-2": {
    "offset": 147.2515,
    "seconds": 0.2
  },
  "foley-zelensky-ready-0": {
    "offset": 147.4915,
    "seconds": 0.2
  },
  "foley-zelensky-ready-1": {
    "offset": 147.7315,
    "seconds": 0.2
  },
  "foley-zelensky-ready-2": {
    "offset": 147.9715,
    "seconds": 0.2
  },
  "foley-bilozerska-step-0": {
    "offset": 148.2115,
    "seconds": 0.2
  },
  "foley-bilozerska-step-1": {
    "offset": 148.4515,
    "seconds": 0.2
  },
  "foley-bilozerska-step-2": {
    "offset": 148.6915,
    "seconds": 0.2
  },
  "foley-bilozerska-climb-0": {
    "offset": 148.9315,
    "seconds": 0.2
  },
  "foley-bilozerska-climb-1": {
    "offset": 149.1715,
    "seconds": 0.2
  },
  "foley-bilozerska-climb-2": {
    "offset": 149.4115,
    "seconds": 0.2
  },
  "foley-bilozerska-jump-0": {
    "offset": 149.6515,
    "seconds": 0.2
  },
  "foley-bilozerska-jump-1": {
    "offset": 149.8915,
    "seconds": 0.2
  },
  "foley-bilozerska-jump-2": {
    "offset": 150.1315,
    "seconds": 0.2
  },
  "foley-bilozerska-land-0": {
    "offset": 150.3715,
    "seconds": 0.26
  },
  "foley-bilozerska-land-1": {
    "offset": 150.6715,
    "seconds": 0.26
  },
  "foley-bilozerska-land-2": {
    "offset": 150.9715,
    "seconds": 0.26
  },
  "foley-bilozerska-hurt-0": {
    "offset": 151.2715,
    "seconds": 0.2
  },
  "foley-bilozerska-hurt-1": {
    "offset": 151.5115,
    "seconds": 0.2
  },
  "foley-bilozerska-hurt-2": {
    "offset": 151.7515,
    "seconds": 0.2
  },
  "foley-bilozerska-ready-0": {
    "offset": 151.9915,
    "seconds": 0.2
  },
  "foley-bilozerska-ready-1": {
    "offset": 152.2315,
    "seconds": 0.2
  },
  "foley-bilozerska-ready-2": {
    "offset": 152.4715,
    "seconds": 0.2
  },
  "foley-it-army-step-0": {
    "offset": 152.7115,
    "seconds": 0.2
  },
  "foley-it-army-step-1": {
    "offset": 152.9515,
    "seconds": 0.2
  },
  "foley-it-army-step-2": {
    "offset": 153.1915,
    "seconds": 0.2
  },
  "foley-it-army-climb-0": {
    "offset": 153.4315,
    "seconds": 0.2
  },
  "foley-it-army-climb-1": {
    "offset": 153.6715,
    "seconds": 0.2
  },
  "foley-it-army-climb-2": {
    "offset": 153.9115,
    "seconds": 0.2
  },
  "foley-it-army-jump-0": {
    "offset": 154.1515,
    "seconds": 0.2
  },
  "foley-it-army-jump-1": {
    "offset": 154.3915,
    "seconds": 0.2
  },
  "foley-it-army-jump-2": {
    "offset": 154.6315,
    "seconds": 0.2
  },
  "foley-it-army-land-0": {
    "offset": 154.8715,
    "seconds": 0.26
  },
  "foley-it-army-land-1": {
    "offset": 155.1715,
    "seconds": 0.26
  },
  "foley-it-army-land-2": {
    "offset": 155.4715,
    "seconds": 0.26
  },
  "foley-it-army-hurt-0": {
    "offset": 155.7715,
    "seconds": 0.2
  },
  "foley-it-army-hurt-1": {
    "offset": 156.0115,
    "seconds": 0.2
  },
  "foley-it-army-hurt-2": {
    "offset": 156.2515,
    "seconds": 0.2
  },
  "foley-it-army-ready-0": {
    "offset": 156.4915,
    "seconds": 0.2
  },
  "foley-it-army-ready-1": {
    "offset": 156.7315,
    "seconds": 0.2
  },
  "foley-it-army-ready-2": {
    "offset": 156.9715,
    "seconds": 0.2
  },
  "foley-skovoroda-step-0": {
    "offset": 157.2115,
    "seconds": 0.2
  },
  "foley-skovoroda-step-1": {
    "offset": 157.4515,
    "seconds": 0.2
  },
  "foley-skovoroda-step-2": {
    "offset": 157.6915,
    "seconds": 0.2
  },
  "foley-skovoroda-climb-0": {
    "offset": 157.9315,
    "seconds": 0.2
  },
  "foley-skovoroda-climb-1": {
    "offset": 158.1715,
    "seconds": 0.2
  },
  "foley-skovoroda-climb-2": {
    "offset": 158.4115,
    "seconds": 0.2
  },
  "foley-skovoroda-jump-0": {
    "offset": 158.6515,
    "seconds": 0.2
  },
  "foley-skovoroda-jump-1": {
    "offset": 158.8915,
    "seconds": 0.2
  },
  "foley-skovoroda-jump-2": {
    "offset": 159.1315,
    "seconds": 0.2
  },
  "foley-skovoroda-land-0": {
    "offset": 159.3715,
    "seconds": 0.26
  },
  "foley-skovoroda-land-1": {
    "offset": 159.6715,
    "seconds": 0.26
  },
  "foley-skovoroda-land-2": {
    "offset": 159.9715,
    "seconds": 0.26
  },
  "foley-skovoroda-hurt-0": {
    "offset": 160.2715,
    "seconds": 0.2
  },
  "foley-skovoroda-hurt-1": {
    "offset": 160.5115,
    "seconds": 0.2
  },
  "foley-skovoroda-hurt-2": {
    "offset": 160.7515,
    "seconds": 0.2
  },
  "foley-skovoroda-ready-0": {
    "offset": 160.9915,
    "seconds": 0.2
  },
  "foley-skovoroda-ready-1": {
    "offset": 161.2315,
    "seconds": 0.2
  },
  "foley-skovoroda-ready-2": {
    "offset": 161.4715,
    "seconds": 0.2
  }
} as const;
export type SfxId=keyof typeof SFX_ASSETS;
