import test from 'node:test';import assert from 'node:assert/strict';
import {World,IDLE} from '../src/game/world.ts';import {addInfantry} from '../src/game/infantry.ts';import {Gore} from '../src/game/enemy-death.ts';import {SnapshotWriter,applySnapshot} from '../src/game/coop-state.ts';
function setup(hero:'klychko'|'taira'){const w=new World(0,[hero],hero);w.mode='playing';w.enemies=[];w.mounts=[];w.allies=[];w.ladders=[];w.boxes=[{id:9999,x:20,y:-1,w:80,h:1,hp:Infinity,maxHp:Infinity,kind:'earth'}];w.player.x=20;w.player.invulnerable=999;return w;}
const frames=(w:World,n:number,a=IDLE)=>{for(let i=0;i<n;i++)w.step(1/60,a);};
test('quick punches leave full-health infantry alive; charged finish sends directional death',()=>{
 for(const hero of ['klychko','taira'] as const){const w=setup(hero),e=addInfantry(w,'rifle',22);e.infantry!.reaction=100;frames(w,1,{...IDLE,fire:true});frames(w,1);assert.equal(e.hp,96-(hero==='taira'?22:18));assert.ok(e.hp>0);}
 const w=setup('klychko'),e=addInfantry(w,'gunner',22);e.infantry!.reaction=100;frames(w,55,{...IDLE,fire:true});assert.equal(e.hp,160);frames(w,1);assert.ok(e.hp<=0);assert.equal(w.events.find(e=>e.type==='enemyDeath')?.launchDir,1);
});
test('full charge breaks a frontal shield; quick tap only chips it',()=>{
 for(const full of [false,true]){const w=setup('klychko'),e=addInfantry(w,'shield',22);e.infantry!.reaction=100;frames(w,full?55:1,{...IDLE,fire:true});frames(w,1);if(full){assert.equal(e.infantry!.shield,0);assert.ok(e.hp<=0);}else{assert.equal(e.hp,130);assert.equal(e.infantry!.shield,62);}}
});
test('charge cues fire once at gather/ready, and release cancels the gather sound',()=>{const w=setup('klychko');frames(w,90,{...IDLE,fire:true});assert.equal(w.events.filter(e=>e.sfx==='klychko-gather-v5').length,1);assert.equal(w.events.filter(e=>e.sfx==='klychko-ready-v4').length,1);frames(w,1);assert.equal(w.events.filter(e=>e.sfx==='klychko-charge-stop').length,1);const short=setup('klychko');frames(short,1,{...IDLE,fire:true});frames(short,1);assert.equal(short.events.filter(e=>e.sfx==='klychko-gather-v5').length,0);});
test('aid station heals group over time, stops at range/cover, never revives dead bodies',()=>{const w=setup('taira');const p2=w.addPlayer('usyk');p2.body.x=22;w.player.hp=30;p2.body.hp=40;frames(w,1,{...IDLE,special:true});assert.equal(w.player.hp,50);assert.equal(p2.body.hp,60);p2.body.x=32;frames(w,180);assert.equal(w.player.hp,65);assert.equal(p2.body.hp,60);
 const wall=setup('taira');wall.player.hp=50;const friend=wall.addPlayer('usyk');friend.body.x=23;friend.body.hp=50;wall.boxes.push({id:9998,x:21.5,y:0,w:.5,h:4,hp:Infinity,maxHp:Infinity,kind:'stone'});frames(wall,1,{...IDLE,special:true});assert.equal(wall.player.hp,50);assert.equal(friend.body.hp,70);friend.body.hp=0;frames(wall,180);assert.equal(friend.body.hp,0);
});
test('placed medical field freezes on pause and survives host snapshots',()=>{const w=setup('taira');w.addPlayer('usyk');w.player.hp=40;frames(w,1,{...IDLE,special:true});const f=w.effects[0],x=f.x;w.player.x+=10;frames(w,20);assert.equal(f.x,x);w.mode='paused';const hp=w.player.hp,age=f.age;frames(w,90);assert.equal(w.player.hp,hp);assert.equal(f.age,age);const guest=setup('taira');applySnapshot(guest,JSON.parse(JSON.stringify(new SnapshotWriter(w).snapshot(1))));assert.equal(guest.effects[0].x,x);assert.equal(guest.effects[0].age,age);});
test('heavy finish sprays fragments forward without changing the particle cap',()=>{const g=new Gore();g.burst(0,0,()=>.5,-1);assert.ok(g.bits.every(b=>b.vx<0));for(let i=0;i<20;i++)g.burst(0,0,()=>.5,1);assert.ok(g.bits.length<=420);});
