import test from 'node:test';
import assert from 'node:assert/strict';
import {World,IDLE} from '../src/game/world.ts';
import {HEROES} from '../src/game/content.ts';
import {launchEffect} from '../src/game/hero-combat.ts';
import {hostileBlast} from '../src/game/enemies.ts';
import {summonFollowers} from '../src/game/followers.ts';
import {addMount,damageMount} from '../src/game/mounts.ts';
import {SnapshotWriter,applySnapshot,RemoteInput,cleanActions} from '../src/game/coop-state.ts';
function pair(){const w=new World(0,HEROES.map(h=>h.id));w.addPlayer('lesya');w.mode='playing';w.enemies=[];w.boxes=w.boxes.filter(b=>b.y<0);return w;}
test('two players move independently while the world clock advances once',()=>{const w=pair();for(let i=0;i<30;i++)w.stepPlayers(1/60,[{...IDLE,move:1},{...IDLE,move:-1}]);assert.ok(w.players[0].body.x>5);assert.ok(w.players[1].body.x<3);assert.ok(Math.abs(w.time-.5)<1e-9);assert.equal(w.actor.id,0);assert.throws(()=>w.addPlayer());});
test('second player has real projectiles, magazine, special and ultimate ownership',()=>{const w=pair();w.stepPlayers(1/60,[IDLE,{...IDLE,fire:true,special:true,ultimate:true}]);assert.equal(w.players[0].body.energy,100);assert.equal(w.players[1].body.energy,0);assert.ok(w.bullets.some(b=>b.hero==='lesya'));assert.ok(w.effects.length>=2);assert.ok(w.effects.every(f=>f.playerId===1));assert.equal(w.players[1].body.specialRecovery.length,1);});
test('enemy projectile and hostile explosion can hit guest; guest respawn preserves host state',()=>{const w=pair();w.players[1].body.x=8;w.bullets.push({id:w.nextId(),x:7,y:1,vx:60,vy:0,life:.2,friendly:false,damage:15});w.stepPlayers(1/60,[IDLE,IDLE]);assert.equal(w.players[1].body.hp,85);assert.equal(w.player.hp,100);w.players[1].body.invulnerable=0;hostileBlast(w,8,1,1,30);assert.equal(w.players[1].body.hp,55);w.players[1].checkpoint=6;w.players[1].body.invulnerable=0;w.withPlayer(1,()=>w.damagePlayer(100));assert.equal(w.players[1].body.x,6);assert.equal(w.players[0].body.hp,100);assert.equal(w.mode,'playing');});
test('duplicate heroes own separate followers and clearing a kit keeps partner summons',()=>{const w=pair();w.players[1].heroId='shevchenko';summonFollowers(w,'infantry');w.withPlayer(1,()=>summonFollowers(w,'infantry'));assert.equal(w.followers.length,4);w.withPlayer(1,()=>w.clearOwned());assert.equal(w.followers.length,2);assert.ok(w.followers.every(f=>f.playerId===0));});
test('only one driver claims a tank; destroyed guest tank ejects its actual driver',()=>{const w=pair();w.mounts=[];const tank=addMount(w,4);w.stepPlayers(1/60,[{...IDLE,interact:true},{...IDLE,interact:true}]);assert.equal(w.players.filter(a=>a.mounted).length,1);w.players[0].mounted=null;w.players[1].mounted=tank;damageMount(w,tank,999);assert.equal(w.players[1].mounted,null);assert.ok(w.players[1].body.vy>0);});
test('second-player transformations follow second-player position',()=>{const w=pair();w.players[1].body.x=12;w.withPlayer(1,()=>launchEffect(w,'ultimate'));w.stepPlayers(1/60,[IDLE,{...IDLE,move:1}]);const effect=w.effects.find(f=>f.hero==='lesya')!;assert.equal(effect.x,w.players[1].body.x);});
test('snapshot round trip preserves destruction, two kits, mounts, effect Sets and events',()=>{const w=pair(),writer=new SnapshotWriter(w);w.boxes[0].hp=0;w.withPlayer(1,()=>launchEffect(w,'special'));const guest=new World();const snapshot=JSON.parse(JSON.stringify(writer.snapshot(1,[{type:'shot',x:2,y:1}])));applySnapshot(guest,snapshot);assert.equal(guest.players.length,2);assert.equal(guest.actor.id,1);assert.equal(guest.boxes.find(b=>b.id===w.boxes[0].id)!.hp,0);assert.ok(guest.effects[0].hit instanceof Set);assert.equal(guest.events[0].type,'shot');assert.equal(guest.heroId,'lesya');assert.ok(JSON.stringify(snapshot).length<64000);});
test('remote inputs reject invalid values, retain edge until one tick, expire held fire',()=>{const input=new RemoteInput();assert.equal(cleanActions({...IDLE,move:Infinity}),null);assert.equal(input.receive(0,{...IDLE,move:200,jump:true,fire:true},1),true);input.receive(1,{...IDLE,move:1,fire:true},1.01);assert.equal(input.take(1.02).jump,true);assert.equal(input.take(1.03).jump,false);assert.equal(input.receive(0,{...IDLE},1.1),false);assert.equal(input.take(1.5).fire,false);});
test('second player can trigger a boss arena and both stay inside with supplies',()=>{const w=new World(1);w.addPlayer();w.mode='playing';const b=w.boss!;w.players[1].body.x=b.x;w.stepPlayers(1/60,[IDLE,IDLE]);assert.equal(w.mode,'cinematic');assert.ok(w.players[0].body.x>100);assert.ok(w.players[1].body.x>100);assert.equal(w.time,0);});
