import test from 'node:test';import assert from 'node:assert/strict';
import {World,IDLE} from '../src/game/world.ts';import {HEROES,type HeroId} from '../src/game/content.ts';import {parseProgress} from '../src/game/storage.ts';import {SFX_ASSETS} from '../src/game/sfx-assets.ts';
function setup(id:HeroId){const w=new World(0,HEROES.map(h=>h.id),id);w.mode='playing';w.boxes=w.boxes.filter(b=>b.y<0);w.player.x=5;w.enemies=w.enemies.slice(0,2);w.enemies.forEach((e,i)=>{e.x=8+i*3;e.y=0;e.hp=e.maxHp=180;e.cooldown=99;e.infantry!.cooldown=99;});return w;}
function advance(w:World,n:number){for(let i=0;i<n;i++)w.step(1/60,IDLE);}
test('Shevchenko special stuns for three seconds without consuming ultimate or damaging foes',()=>{const w=setup('shevchenko');w.step(1/60,{...IDLE,special:true});assert.equal(w.enemies[0].hp,180);assert.ok(w.enemies[0].rooted!>2.9);assert.equal(w.player.energy,100);assert.ok(w.player.specialCooldown>7);advance(w,190);assert.equal(w.enemies[0].rooted,0);});
test('Shevchenko ultimate telegraphs then strikes three columns, no repeated damage each frame',()=>{const w=setup('shevchenko');w.enemies[0].x=7;w.enemies[1].x=11;w.enemies.forEach(e=>e.hp=500);w.step(1/60,{...IDLE,ultimate:true});assert.equal(w.enemies[0].hp,500);assert.equal(w.player.specialCooldown,0);advance(w,34);assert.equal(w.enemies[0].hp,500);advance(w,60);assert.equal(w.enemies[0].hp,320);assert.equal(w.enemies[1].hp,320);assert.equal(w.events.filter(e=>e.type==='thunder').length,3);});
test('Lesya arrows apply timed poison, which damages after arrow impact',()=>{const w=setup('lesya');w.step(1/60,{...IDLE,fire:true});advance(w,8);const hp=w.enemies[0].hp;assert.ok(w.enemies[0].poison!>0);advance(w,190);assert.ok(w.enemies[0].hp<hp-45);assert.equal(w.enemies[0].poison,0);assert.ok(Math.abs(w.enemies[0].hp-102)<.01);});
test('Lesya crows redirect hostile fire upward without rooting or damaging foes',()=>{const w=setup('lesya');w.enemies[0].cooldown=0;w.enemies[0].infantry!.cooldown=0;w.step(1/60,{...IDLE,special:true});advance(w,80);assert.ok(w.enemies[0].distracted!>0);assert.equal(w.enemies[0].hp,180);assert.equal(w.enemies[0].rooted,0);assert.ok(w.bullets.some(b=>!b.friendly&&b.vy>0));});
test('Mavka follows the hero, roots nearby foes, and expires without passive healing',()=>{const w=setup('lesya');w.player.hp=40;w.step(1/60,{...IDLE,ultimate:true});assert.ok(w.player.form>5.9);w.player.x=12;advance(w,60);assert.equal(w.effects[0].x,w.player.x);assert.ok(w.enemies[1].rooted!>0);assert.ok(w.enemies[1].hp<180);assert.equal(w.player.hp,40);advance(w,310);assert.equal(w.player.form,0);assert.equal(w.effects.length,0);});
test('Franko special intercepts bullets but leaves enemies and cover intact',()=>{const w=setup('franko');w.bullets.push({id:888,x:7,y:1,vx:-12,vy:0,life:2,friendly:false,damage:15});w.step(1/60,{...IDLE,special:true});assert.equal(w.bullets.length,0);assert.equal(w.enemies[0].hp,180);assert.equal(w.player.energy,100);});
test('Franko ultimate breaks cover on both sides without digging out his footing',()=>{const w=setup('franko');w.enemies[0].x=2;w.enemies[1].x=11;const b={id:999,x:10,y:0,w:1,h:2,hp:150,maxHp:150,kind:'stone' as const};w.boxes.push(b);w.step(1/60,{...IDLE,ultimate:true});assert.equal(b.hp,150);advance(w,35);assert.ok(b.hp<=0);assert.ok(w.enemies.every(e=>e.hp<=0));assert.ok(w.boxes.filter(b=>b.y<0).every(b=>b.hp>0));});
test('special and ultimate have separate budgets; pause freezes both and effects',()=>{const w=setup('lesya');w.step(1/60,{...IDLE,special:true,ultimate:true});assert.equal(w.effects.length,2);const state=JSON.stringify([w.effects.map(f=>[f.age,f.life]),w.player]);w.mode='paused';advance(w,100);assert.equal(JSON.stringify([w.effects.map(f=>[f.age,f.life]),w.player]),state);w.mode='playing';w.step(1/60,{...IDLE,special:true,ultimate:true});assert.equal(w.effects.length,2);});
test('rescue cancels the previous hero transformation and lingering abilities',()=>{const w=setup('lesya');w.step(1/60,{...IDLE,ultimate:true});w.player.x=w.allies[0].x;w.player.y=0;w.step(1/60,{...IDLE,interact:true});assert.equal(w.heroId,'franko');assert.equal(w.player.form,0);assert.equal(w.effects.length,0);});
test('the original three heroes retain distinct cadence, range and sound character',()=>{const ranges=HEROES.slice(0,3).map(h=>h.projectileSpeed*h.projectileLife);assert.equal(new Set(ranges).size,3);assert.equal(new Set(HEROES.slice(0,3).map(h=>h.cooldown)).size,3);assert.equal(new Set(HEROES.slice(0,3).map(h=>SFX_ASSETS[`${h.id}-weapon-0`].offset)).size,3);});
test('legacy generic roster migrates without losing rescue unlocks',()=>{const p=parseProgress('{"mission":2,"hero":"scout","unlocked":["kozak","kharakternyk","scout"]}');assert.deepEqual(p.unlocked,['shevchenko','lesya','franko']);assert.equal(p.hero,'franko');assert.equal(p.mission,2);});
test('held upward input cannot recapture ladder after jump lock expires',()=>{const w=setup('shevchenko');w.player.x=18;w.player.y=3;w.step(1/60,{...IDLE,climb:1});w.step(1/60,{...IDLE,climb:1,jump:true});for(let i=0;i<35;i++){w.player.x=18;w.step(1/60,{...IDLE,climb:1});assert.equal(w.player.ladder,-1);}w.step(1/60,IDLE);w.player.x=18;w.player.y=3;w.step(1/60,{...IDLE,climb:1});assert.equal(w.player.ladder,0);});
