import test from 'node:test';import assert from 'node:assert/strict';
import {World,IDLE,type Enemy} from '../src/game/world.ts';
import {HEROES,ACTIVE_HEROES,type HeroId} from '../src/game/content.ts';
import {addVehicle,enemyActive} from '../src/game/enemies.ts';
import {launchEffect} from '../src/game/hero-combat.ts';
import {grenade} from '../src/game/hero-expansion.ts';
import {SnapshotWriter,applySnapshot} from '../src/game/coop-state.ts';
function world(id:HeroId){const w=new World(0,HEROES.map(h=>h.id),id);w.mode='playing';w.player.x=20;w.player.y=0;w.player.invulnerable=0;w.enemies=[];w.mounts=[];w.allies=[];w.boxes=[{id:900000,x:50,y:-1,w:100,h:1,kind:'earth',hp:Infinity,maxHp:Infinity}];w.ladders=[];w.ammoCrates=[];return w;}
function enemy(w:World,x:number,y=0){const e:Enemy={id:w.nextId(),x,y,hp:1000,maxHp:1000,dir:-1,anchor:x,heavy:false,windup:0,cooldown:999};w.enemies.push(e);return e;}
function run(w:World,n:number,action=IDLE){for(let i=0;i<n;i++)w.step(1/60,action);}
test('Bayraktar remains active; reserve identities stay available for saved games and practice',()=>{assert.ok(ACTIVE_HEROES.some(h=>h.id==='bayraktar'));assert.ok(!ACTIVE_HEROES.some(h=>h.id==='ghost'));assert.ok(HEROES.some(h=>h.id==='ghost'));assert.equal(new World(0,['ghost'],'ghost').heroId,'ghost');});
test('two homing drones split targets, ignore distant enemies and follow when no target exists',()=>{const w=world('bayraktar');enemy(w,30);enemy(w,31,3);launchEffect(w,'special');launchEffect(w,'special');run(w,1);assert.equal(new Set(w.effects.map(f=>f.target)).size,2);const far=world('bayraktar');enemy(far,60);launchEffect(far,'special');run(far,30);assert.equal(far.effects[0].target,undefined);assert.ok(Math.abs(far.effects[0].x-far.player.x)<3);});
test('Usyk hits locally and his dash respects solid walls',()=>{const w=world('usyk'),near=enemy(w,22),far=enemy(w,30);w.step(1/60,{...IDLE,fire:true});assert.ok(near.hp<1000);assert.equal(far.hp,1000);assert.equal(w.bullets.length,0);w.boxes.push({id:900001,x:23,y:0,w:1,h:8,kind:'stone',hp:Infinity,maxHp:Infinity});w.step(1/60,{...IDLE,special:true});run(w,30);assert.ok(w.player.x<22.3);});
test('grenades arc, bounce once, expire and do not damage owner',()=>{const w=world('almaziv');grenade(w);const b=w.bullets[0];run(w,15);assert.ok(b.y>2);run(w,62);assert.equal(b.bounces,0);assert.ok(w.events.some(e=>e.sfx==='grenade-bounce'));run(w,40);assert.equal(w.bullets.length,0);assert.equal(w.player.hp,100);});
test('Klitschko blocks only front bullets and time slow leaves player motion unchanged',()=>{const w=world('klychko');w.bullets.push({id:500,x:21,y:1,vx:-10,vy:0,life:1,friendly:false,damage:20});w.step(1/60,{...IDLE,special:true});assert.equal(w.bullets.length,0);assert.ok(w.events.some(e=>e.sfx==='klychko-special'));const a=world('klychko'),b=world('klychko');a.step(1/60,{...IDLE,ultimate:true});run(a,30,{...IDLE,move:1});run(b,30,{...IDLE,move:1});assert.ok(Math.abs(a.player.x-b.player.x)<.01);});
test('Taira conserves charges when everyone is healthy; heals wounded teammate before self',()=>{const w=world('taira'),p2=w.addPlayer('usyk');p2.body.x=22;w.stepPlayers(1/60,[{...IDLE,special:true},IDLE]);assert.equal(w.specialCharges,2);w.player.hp=30;p2.body.hp=40;w.stepPlayers(1/60,[{...IDLE,special:true},IDLE]);assert.equal(p2.body.hp,65);assert.equal(w.player.hp,30);assert.equal(w.specialCharges,1);});
test('Prytula delivers one shared finite-ammo tank and cannot refill by recasting',()=>{const w=world('prytula');w.step(1/60,{...IDLE,ultimate:true});run(w,75);assert.equal(w.mounts.length,1);assert.equal(w.mounts[0].armor,200);assert.equal(w.mounts[0].rounds,8);w.player.energy=100;w.step(1/60,{...IDLE,ultimate:true});assert.equal(w.player.energy,100);run(w,75);assert.equal(w.mounts.length,1);});
test('IT hijacks an actual tank temporarily',()=>{const w=world('it-army'),tank=addVehicle(w,'tank',27,0);tank.vehicle!.active=true;w.step(1/60,{...IDLE,special:true});assert.equal(tank.hacked?.playerId,0);assert.equal(enemyActive(tank),false);assert.equal(w.followers.length,0);run(w,485);assert.equal(tank.hacked,undefined);assert.equal(enemyActive(tank),true);});
test('two IT players each get their own fallback without a radio',()=>{const w=world('it-army');w.addPlayer('it-army');w.stepPlayers(1/60,[{...IDLE,special:true},{...IDLE,special:true}]);assert.equal(w.followers.length,2);assert.deepEqual(w.followers.map(f=>f.playerId),[0,1]);});
test('prepared sniper shot is stronger but still hits only one target',()=>{const w=world('bilozerska');enemy(w,25);enemy(w,27);run(w,55);w.step(1/60,{...IDLE,fire:true});run(w,10);assert.equal(w.enemies[0].hp,890);assert.equal(w.enemies[1].hp,1000);});
test('new abilities, tank rounds and hack allegiance survive JSON snapshot',()=>{const w=world('prytula');w.addPlayer('it-army');w.stepPlayers(1/60,[{...IDLE,ultimate:true},{...IDLE,special:true}]);for(let i=0;i<80;i++)w.stepPlayers(1/60,[IDLE,IDLE]);const guest=world('prytula');applySnapshot(guest,JSON.parse(JSON.stringify(new SnapshotWriter(w).snapshot(1))));assert.equal(guest.players.length,2);assert.equal(guest.mounts[0].rounds,8);assert.equal(guest.followers[0].playerId,1);});
test('all new melee fighters can break cover without punching through solid walls',()=>{for(const id of ['usyk','klychko','taira','franko'] as HeroId[]){const w=world(id);w.boxes.push({id:900002,x:22,y:0,w:1,h:2,kind:'crate',hp:30,maxHp:30});const e=enemy(w,23);w.step(1/60,{...IDLE,fire:true});assert.ok(w.boxes[1].hp<=0,id);assert.equal(e.hp,1000,id);}});
test('captured tanks take hostile damage but reject friendly hero damage',()=>{const w=world('it-army'),tank=addVehicle(w,'tank',25,0);tank.vehicle!.active=true;w.step(1/60,{...IDLE,special:true});const hp=tank.hp;w.damageEnemy(tank,50);assert.equal(tank.hp,hp);w.damageEnemy(tank,50,'combat',true);assert.equal(tank.hp,hp-50);});
test('tank delivery works on tile edges, keeps its marked site',()=>{const w=new World(0,['prytula'], 'prytula');w.mode='playing';w.player.x=65;w.enemies=[];w.boxes=w.boxes.filter(b=>b.y<0);w.step(1/60,{...IDLE,ultimate:true});assert.equal(w.player.energy,0);const marker=w.effects[0].x;w.player.x+=10;run(w,75);assert.equal(w.mounts.at(-1)!.x,marker);assert.equal(w.mounts.at(-1)!.rounds,8);});
test('moving sniper loses prepared-shot bonus immediately',()=>{const w=world('bilozerska');enemy(w,25);run(w,55);w.step(1/60,{...IDLE,fire:true,move:1});run(w,10);assert.equal(w.enemies[0].hp,918);});
test('rescue clears a previous fighter’s dash and charge state',()=>{const w=world('usyk');w.unlocked=['usyk'];w.allies=[{x:20,rescued:false}];w.player.dashTime=.2;w.player.mamaiHold=.2;w.step(1/60,{...IDLE,interact:true});assert.equal(w.player.dashTime,0);assert.equal(w.player.mamaiHold,0);});
