import test from 'node:test';import assert from 'node:assert/strict';
import {World,IDLE} from '../src/game/world.ts';import {addInfantry} from '../src/game/infantry.ts';import {SnapshotWriter,applySnapshot} from '../src/game/coop-state.ts';
function fixture(hero:'usyk'|'klychko'='klychko'){const w=new World(0,[hero],hero);w.mode='playing';w.player.x=20;w.player.invulnerable=999;w.enemies=[];w.mounts=[];w.allies=[];w.boxes=[{id:9000,x:20,y:-1,w:50,h:1,hp:Infinity,maxHp:Infinity,kind:'earth'}];w.ladders=[];return w;}
function run(w:World,n:number,a=IDLE){for(let i=0;i<n;i++)w.step(1/60,a);}
function target(w:World){const e=addInfantry(w,'rifle',22);e.hp=e.maxHp=1000;e.infantry!.reaction=100;e.infantry!.memory=100;e.infantry!.lastX=22;return e;}
test('Klitschko charges without auto-punching and releases one heavy strike; Usyk keeps rapid attacks',()=>{const w=fixture(),e=target(w);run(w,65,{...IDLE,fire:true});assert.equal(e.hp,1000);assert.equal(w.shots,0);assert.equal(w.player.klychkoHold,.9);run(w,1);assert.equal(w.shots,1);assert.equal(e.hp,810);run(w,90);assert.equal(w.shots,1);const u=fixture('usyk');target(u);run(u,65,{...IDLE,fire:true});assert.ok(u.shots>=4);});
test('a short tap is weaker than a held punch and charging visibly limits movement',()=>{const w=fixture(),e=target(w);run(w,1,{...IDLE,fire:true});run(w,1);assert.ok(e.hp<1000&&e.hp>940);const a=fixture(),b=fixture();run(a,1,{...IDLE,fire:true});const start=a.player.x;run(a,30,{...IDLE,fire:true,move:1});run(b,30,{...IDLE,move:1});assert.ok(a.player.x-start<(b.player.x-20)*.6);});
test('uppercut launches both fighter and infantry, then gravity returns the target to the floor',()=>{const w=fixture(),e=target(w);run(w,1,{...IDLE,special:true});assert.ok(w.player.vy>0);assert.ok(e.infantry!.knockup);assert.ok(e.infantry!.vy>0);run(w,15);assert.ok(e.y>1&&w.player.y>1);run(w,100);assert.equal(e.y,0);assert.equal(e.infantry!.knockup,false);});
test('slam deals damage and sounds only on actual landing, once; no time slow',()=>{const w=fixture(),e=target(w);w.bullets.push({id:999,x:0,y:12,vx:10,vy:0,life:3,damage:0,friendly:false});run(w,1,{...IDLE,ultimate:true});const x=w.bullets[0].x;run(w,10);assert.equal(e.hp,1000);assert.equal(w.events.filter(e=>e.sfx==='klychko-slam-v2').length,0);assert.ok(Math.abs(w.bullets[0].x-x-10/6)<.01);run(w,90);assert.equal(w.events.filter(e=>e.sfx==='klychko-slam-v2').length,1);assert.ok(e.hp<=780);assert.equal(w.player.energy,0);});
test('pause freezes charge and descending slam; charge cannot survive a hero change',()=>{const w=fixture();run(w,20,{...IDLE,fire:true});w.mode='paused';const before=JSON.stringify(w.player);run(w,120);assert.equal(JSON.stringify(w.player),before);w.mode='playing';w.clearOwned();assert.equal(w.player.klychkoHold,0);run(w,1,{...IDLE,ultimate:true});run(w,25);w.mode='paused';const y=w.player.y;run(w,120);assert.equal(w.player.y,y);});
test('charge and uppercut physics survive serialized host snapshots for both players',()=>{const w=fixture();w.addPlayer('usyk');const e=target(w);run(w,25,{...IDLE,fire:true});const guest=fixture();applySnapshot(guest,JSON.parse(JSON.stringify(new SnapshotWriter(w).snapshot(1))));assert.equal(guest.players[0].body.klychkoHold,w.player.klychkoHold);run(w,1,{...IDLE,special:true});run(w,10);applySnapshot(guest,JSON.parse(JSON.stringify(new SnapshotWriter(w).snapshot(2))));assert.ok(guest.enemies.find(a=>a.id===e.id)!.infantry!.knockup);});
