import test from 'node:test';import assert from 'node:assert/strict';
import worker from '../server/pages-worker.js';
import {cleanIceServers,STUN_SERVERS} from '../src/game/ice.ts';
const request=(origin='https://uaforce.thedimas.com',method='POST')=>new Request('https://uaforce.thedimas.com/api/ice',{method,headers:{Origin:origin,'CF-Connecting-IP':'test'}});
test('ICE filters blocked port 53 and rejects missing TURN credentials',()=>{const servers=cleanIceServers([{urls:['turn:turn.cloudflare.com:53?transport=udp','turns:turn.cloudflare.com:443?transport=tcp'],username:'short',credential:'temporary'},{urls:'turn:bad.example:3478'},{urls:'javascript:alert(1)'}]);assert.equal(servers.length,1);assert.deepEqual(servers[0].urls,['turns:turn.cloudflare.com:443?transport=tcp']);assert.ok(!JSON.stringify(STUN_SERVERS).includes('turn.peerjs.com'));});
test('credential route never interferes with static single-player assets',async()=>{const response=await worker.fetch(new Request('https://uaforce.thedimas.com/media/music.mp3'),{ASSETS:{fetch:()=>new Response('asset')}});assert.equal(await response.text(),'asset');});
test('credential endpoint rejects outside origins and unsupported methods',async()=>{assert.equal((await worker.fetch(request('https://other.example'),{})).status,403);assert.equal((await worker.fetch(request(undefined,'GET'),{})).status,405);assert.equal((await worker.fetch(request(),{})).status,503);});
test('credential endpoint supports local silent browser checks without wildcard CORS',async()=>{const response=await worker.fetch(request('http://127.0.0.1:5178','OPTIONS'),{});assert.equal(response.status,204);assert.equal(response.headers.get('Access-Control-Allow-Origin'),'http://127.0.0.1:5178');assert.equal(response.headers.get('Cache-Control'),'no-store');});
test('TURN master credential remains upstream; client receives only expiring ICE credentials',async()=>{const original=globalThis.fetch;let body,authorization;globalThis.fetch=async(_url,options)=>{body=JSON.parse(options.body);authorization=options.headers.Authorization;return Response.json({iceServers:[{urls:'turns:turn.cloudflare.com:443?transport=tcp',username:'temporary-user',credential:'temporary-password'}],internal:'not-returned'});};try{const response=await worker.fetch(request(),{TURN_KEY_ID:'key-id',TURN_API_TOKEN:'server-master-secret'});assert.equal(response.status,200);assert.equal(body.ttl,7200);assert.equal(authorization,'Bearer server-master-secret');const text=await response.text();assert.ok(text.includes('temporary-password'));assert.ok(!text.includes('server-master-secret'));assert.ok(!text.includes('not-returned'));}finally{globalThis.fetch=original;}});
