import test from 'node:test';import assert from 'node:assert/strict';
import {World,IDLE,type Effect} from '../src/game/world.ts';
import {INFANTRY,addInfantry,frighten,type InfantryKind} from '../src/game/infantry.ts';
import {WEAPONS} from '../src/game/weapons.ts';
import {SnapshotWriter,applySnapshot} from '../src/game/coop-state.ts';
import {addVehicle} from '../src/game/enemies.ts';
function setup(){const w=new World();w.mode='playing';w.enemies=[];w.followers=[];w.allies=[];w.mounts=[];w.ladders=[];w.boxes=[{id:99999,x:70,y:-2,w:140,h:2,hp:Infinity,maxHp:Infinity,kind:'earth'}];w.player.x=20;w.player.invulnerable=999;return w;}
const run=(w:World,t:number)=>{for(let i=0;i<Math.round(t*60);i++)w.step(1/60,IDLE);};
function spell(w:World,playerId=0):Effect{const p=w.players[playerId].body;const f:Effect={playerId,hero:'shevchenko',kind:'special',x:p.x,y:0,dir:1,life:3,age:0,hit:new Set()};w.effects.push(f);return f;}
test('all fresh infantry roles survive one normal hit from every player weapon; roles retain distinct health',()=>{const w=setup();for(const kind of Object.keys(INFANTRY) as InfantryKind[])for(const weapon of Object.values(WEAPONS)){const e=addInfantry(w,kind,40);w.damageEnemy(e,weapon.damage);assert.ok(e.hp>0,kind);assert.equal(e.maxHp,INFANTRY[kind].hp);}assert.ok(INFANTRY.gunner.hp>INFANTRY.rifle.hp);});
test('panic runs away, cancels aim and bursts, screams intermittently, expires with the ability',()=>{const w=setup(),e=addInfantry(w,'assault',23);e.infantry!.burstShots=2;e.windup=.2;spell(w);run(w,2.5);assert.equal(e.infantry!.state,'panic');assert.ok(e.x>35);assert.equal(e.windup,0);assert.equal(e.infantry!.burstShots,0);assert.equal(w.events.filter(e=>e.type==='enemyShot').length,0);const screams=w.events.filter(e=>e.type==='enemyPanic');assert.ok(screams.length>=1&&screams.length<=3);run(w,.6);assert.equal(e.panic,undefined);assert.notEqual(e.infantry!.state,'panic');});
test('flee direction follows the caster even if another co-op player is nearer; snapshot preserves fear',()=>{const w=setup();const p2=w.addPlayer('shevchenko');p2.body.x=30;p2.body.invulnerable=999;const e=addInfantry(w,'rifle',27),f=spell(w,p2.id);frighten(w,e,f);w.player.x=26.5;w.stepPlayers(1/60,[IDLE,IDLE]);assert.ok(e.x<27);assert.equal(e.panic!.playerId,p2.id);const guest=setup();applySnapshot(guest,JSON.parse(JSON.stringify(new SnapshotWriter(w).snapshot(1))));assert.deepEqual(guest.enemies[0].panic,e.panic);assert.equal(guest.enemies[0].infantry!.state,'panic');p2.body.x=22;const before=e.x;w.stepPlayers(1/60,[IDLE,IDLE]);assert.ok(e.x>before);});
test('pausing freezes panic; deleting its source effect ends it on resume',()=>{const w=setup(),e=addInfantry(w,'rifle',23);spell(w);run(w,.1);w.mode='paused';const before=JSON.stringify(e);run(w,5);assert.equal(JSON.stringify(e),before);w.effects=[];w.mode='playing';run(w,.05);assert.equal(e.panic,undefined);assert.equal(w.events.filter(e=>e.type==='enemyShot').length,0);});
test('frightened demolition cancels a lit fuse; vehicles are immune to fear',()=>{const w=setup(),e=addInfantry(w,'demolition',23);e.infantry!.fuse=.1;spell(w);run(w,1);assert.equal(e.infantry!.fuse,-1);assert.ok(e.hp>0);assert.equal(w.events.filter(e=>e.type==='hostileBlast').length,0);const tank=addVehicle(w,'tank',24,0);frighten(w,tank,w.effects[0]);assert.equal(tank.panic,undefined);});
test('panic uses solid collision and never teleports through a tall wall',()=>{const w=setup(),e=addInfantry(w,'rifle',23);w.boxes.push({id:8000,x:26,y:0,w:2,h:8,hp:999,maxHp:999,kind:'wall'});spell(w);run(w,2);assert.ok(e.x<24.8);assert.ok(e.x>23);assert.equal(e.infantry!.state,'panic');assert.equal(w.events.filter(e=>e.type==='enemyShot').length,0);});
