import test from 'node:test';import assert from 'node:assert/strict';
import {World,IDLE,type Box} from '../src/game/world.ts';
import {stepStructures} from '../src/game/structural-physics.ts';
import {SnapshotWriter,applySnapshot} from '../src/game/coop-state.ts';
function fixture(){const w=new World();w.mode='playing';w.enemies=[];w.mounts=[];w.boxes=[];w.player.x=30;const add=(x:number,y:number,width:number,height:number,hp:number,kind:Box['kind']='stone')=>{const b:Box={id:w.nextId(),x,y,w:width,h:height,hp,maxHp:hp,kind};w.boxes.push(b);return b;};add(10,-1,20,1,Infinity,'earth');const pillar=add(8,0,1,4,50),roof=add(10,4,5,1,100);return {w,add,pillar,roof};}
function run(w:World,n=120){for(let i=0;i<n;i++)stepStructures(w,1/60);}
test('a severed supported roof warns, falls and shatters instead of remaining suspended',()=>{const{w,pillar,roof}=fixture();w.damageBox(pillar,50);stepStructures(w,1/60);assert.ok(roof.collapseDelay!>0);assert.equal(roof.y,4);run(w,25);assert.ok(roof.falling&&roof.y<4);run(w);assert.ok(roof.hp<=0);assert.ok(w.events.filter(e=>e.type==='debris').length>=3);});
test('a connected roof stays up while a second column supports it',()=>{const{w,add,pillar,roof}=fixture();add(12,0,1,4,50);w.damageBox(pillar,50);run(w);assert.equal(roof.y,4);assert.equal(roof.hp,100);});
test('falling rubble crushes enemies but never hits them through a permanent floor',()=>{for(const protectedFloor of [false,true]){const{w,add,pillar,roof}=fixture();w.enemies.push({id:w.nextId(),x:10,y:0,hp:150,maxHp:150,dir:1,cooldown:999,windup:0,anchor:10,heavy:false});if(protectedFloor)add(10,2.5,8,.2,Infinity,'platform');w.damageBox(pillar,50);run(w);assert.ok(roof.hp<=0);assert.equal(w.enemies[0].hp,protectedFloor?150:70);}});
test('authored floating platforms and preexisting unconnected scenery are preserved',()=>{const{w,add,pillar}=fixture();const platform=add(15,9,8,.3,Infinity,'platform'),floating=add(19,14,1,1,40);w.damageBox(pillar,50);run(w);assert.equal(platform.hp,Infinity);assert.equal(floating.y,14);assert.equal(floating.hp,40);});
test('pause and reveal freeze structural warning and fall',()=>{const{w,pillar,roof}=fixture();w.damageBox(pillar,50);stepStructures(w,1/60);w.mode='paused';const before=JSON.stringify(roof);for(let i=0;i<120;i++)w.step(1/60,IDLE);assert.equal(JSON.stringify(roof),before);w.mode='playing';w.beginCinematic('boss','iron-warden');for(let i=0;i<120;i++)w.step(1/60,IDLE);assert.equal(JSON.stringify(roof),before);});
test('network snapshots carry falling motion and clear warning after impact',()=>{const{w,pillar,roof}=fixture();w.addPlayer();const writer=new SnapshotWriter(w);const guest=new World();guest.boxes=w.boxes.map(b=>({...b}));w.damageBox(pillar,50);stepStructures(w,1/60);applySnapshot(guest,JSON.parse(JSON.stringify(writer.snapshot(1))));assert.ok(guest.boxes.find(b=>b.id===roof.id)!.collapseDelay!>0);run(w);applySnapshot(guest,JSON.parse(JSON.stringify(writer.snapshot(2))));const b=guest.boxes.find(b=>b.id===roof.id)!;assert.equal(b.collapseDelay,0);assert.equal(b.falling,false);assert.ok(b.hp<=0);});
