import test from 'node:test';import assert from 'node:assert/strict';
import {World,IDLE,type Enemy} from '../src/game/world.ts';
import {SnapshotWriter,applySnapshot} from '../src/game/coop-state.ts';
import {survivalWorld} from '../src/game/survival.ts';
function setup(){const w=new World(0,['taira'],'taira');w.mode='playing';w.enemies=[];w.mounts=[];w.allies=[];w.ladders=[];w.ammoCrates=[];w.boxes=[{id:9999,x:30,y:-1,w:80,h:1,hp:Infinity,maxHp:Infinity,kind:'earth'}];w.player.x=20;w.player.invulnerable=999;return w;}
function foe(w:World,x:number,hp=1000){const e:Enemy={id:w.nextId(),x,y:0,hp,maxHp:hp,dir:-1,anchor:x,heavy:false,windup:0,cooldown:999};w.enemies.push(e);return e;}
function frames(w:World,n:number,a=IDLE){for(let i=0;i<n;i++)w.step(1/60,a);}
const fire=(w:World)=>frames(w,1,{...IDLE,fire:true});
function wall(w:World,x:number,hp=Infinity){w.boxes.push({id:w.nextId(),x,y:0,w:1,h:5,hp,maxHp:hp,kind:'stone'});}
test('Taira kills ordinary infantry with two presses and chains at most three local contacts',()=>{const w=setup(),first=foe(w,22,96),second=foe(w,24),third=foe(w,26),fourth=foe(w,28);fire(w);assert.equal(first.hp,44);assert.equal(second.hp,964);assert.equal(third.hp,976);assert.equal(fourth.hp,1000);assert.equal(w.effects[0].links?.length,3);assert.ok(first.ionized!>3.9);frames(w,26);fire(w);assert.ok(first.hp<=0);assert.equal(w.shots,2);});
test('arc respects facing, solid cover, initial range and maximum hop distance',()=>{const w=setup(),behind=foe(w,18),far=foe(w,30);fire(w);assert.equal(behind.hp,1000);assert.equal(far.hp,1000);const cover=setup(),hidden=foe(cover,23);wall(cover,22,40);fire(cover);assert.equal(hidden.hp,1000);assert.ok(cover.boxes[1].hp<=0);const hop=setup(),near=foe(hop,22),distant=foe(hop,25);fire(hop);assert.equal(near.hp,948);assert.equal(distant.hp,1000);const blocked=setup();foe(blocked,22);const next=foe(blocked,24);wall(blocked,23);fire(blocked);assert.equal(next.hp,1000);});
test('three battery shots trigger one real reload; holding never repeats a discharge',()=>{const w=setup();foe(w,22);frames(w,180,{...IDLE,fire:true});assert.equal(w.shots,1);for(let i=0;i<2;i++){frames(w,26);fire(w);}assert.equal(w.player.ammo,0);assert.equal(w.player.reloading,1.8);frames(w,100,{...IDLE,fire:true});assert.equal(w.shots,3);assert.equal(w.player.ammo,0);frames(w,9,{...IDLE,fire:true});assert.equal(w.player.ammo,3);assert.equal(w.shots,3);assert.equal(w.events.filter(e=>e.type==='reloadStart').length,1);assert.equal(w.events.filter(e=>e.type==='reloadEnd').length,1);});
test('ionized marks expire in simulation time and pause freezes them',()=>{const w=setup(),e=foe(w,22);fire(w);w.mode='paused';const left=e.ionized;frames(w,300);assert.equal(e.ionized,left);w.mode='playing';frames(w,241);assert.equal(e.ionized,0);});
test('overload waits for its detonation, hits once and works without marks; it does not heal living players',()=>{const w=setup(),e=foe(w,23);w.player.hp=40;frames(w,1,{...IDLE,ultimate:true});frames(w,18);assert.equal(e.hp,1000);assert.equal(w.player.energy,0);frames(w,4);assert.equal(e.hp,850);assert.equal(w.player.hp,40);frames(w,60);assert.equal(e.hp,850);assert.equal(w.events.filter(e=>e.sfx==='taira-overload-v1').length,1);frames(w,1,{...IDLE,ultimate:true});assert.equal(w.effects.filter(f=>f.kind==='ultimate').length,0);});
test('marked detonation chains visually but overlapping marks cannot multiply damage beyond 250',()=>{const w=setup(),a=foe(w,22),b=foe(w,24),c=foe(w,26);a.ionized=b.ionized=c.ionized=4;frames(w,1,{...IDLE,ultimate:true});frames(w,23);assert.deepEqual([a.hp,b.hp,c.hp],[750,750,750]);assert.deepEqual([a.ionized,b.ionized,c.ionized],[0,0,0]);assert.equal(w.effects.filter(f=>f.power===2).length,3);assert.equal(w.effects.find(f=>f.kind==='ultimate')?.links?.length,3);});
test('overload respects cover before breaking it; marked targets and distant enemies behind walls stay safe',()=>{const w=setup(),hidden=foe(w,24),far=foe(w,35);hidden.ionized=4;wall(w,22,100);frames(w,1,{...IDLE,ultimate:true});frames(w,23);assert.equal(hidden.hp,1000);assert.equal(far.hp,1000);assert.ok(hidden.ionized!>0);assert.ok(w.boxes[1].hp<=0);});
test('two-player JSON snapshots preserve marks, arc endpoints, ammo and detonation state',()=>{const w=setup();w.addPlayer('usyk');foe(w,22);fire(w);const guest=setup();applySnapshot(guest,JSON.parse(JSON.stringify(new SnapshotWriter(w).snapshot(1))));assert.equal(guest.enemies[0].ionized,w.enemies[0].ionized);assert.deepEqual(guest.effects[0].links,w.effects[0].links);assert.equal(guest.players[0].body.ammo,2);frames(w,1,{...IDLE,ultimate:true});frames(w,23);applySnapshot(guest,JSON.parse(JSON.stringify(new SnapshotWriter(w).snapshot(2))));assert.equal(guest.effects.find(f=>f.kind==='ultimate')?.impactAge,w.effects.find(f=>f.kind==='ultimate')?.impactAge);});
test('overload preserves the fallen-partner rescue in survival',()=>{const w=survivalWorld('taira','usyk');w.mode='playing';w.players[1].body.hp=0;w.players[1].lives=0;frames(w,1,{...IDLE,ultimate:true});assert.equal(w.players[1].body.hp,35);assert.equal(w.players[1].lives,1);assert.equal(w.player.energy,0);});
