import test from 'node:test';import assert from 'node:assert/strict';
import {World,IDLE,type Enemy} from '../src/game/world.ts';import {HEROES,type HeroId} from '../src/game/content.ts';import {WEAPONS} from '../src/game/weapons.ts';import {abilityStates} from '../src/game/hud.ts';import {padActions,freshBindings} from '../src/game/input.ts';
function world(id:HeroId){const w=new World(0,HEROES.map(h=>h.id),id);w.mode='playing';w.enemies=[];w.boxes=w.boxes.filter(b=>b.y<0);w.player.x=5;return w;}
function run(w:World,n:number,fire=false){for(let i=0;i<n;i++)w.step(1/60,{...IDLE,fire});}
function target(w:World,x:number,hp=1000){const e:Enemy={id:w.nextId(),x,y:0,hp,maxHp:hp,dir:-1,cooldown:999,windup:0,anchor:x,heavy:false};w.enemies.push(e);return e;}
function empty(w:World){for(let i=0;i<4000&&!w.player.reloading;i++)w.step(1/60,{...IDLE,fire:w.hero.mode==='single'?!w.player.weaponTrigger:true});assert.equal(w.player.ammo,0);assert.equal(w.shots,w.hero.magazine);}
for(const h of HEROES.filter(h=>h.magazine>0))test(h.id+' empties a finite magazine, blocks fire, and reloads exactly once',()=>{const w=world(h.id);empty(w);const shots=w.shots;assert.equal(w.events.filter(e=>e.type==='reloadStart').length,1);assert.equal(abilityStates(w)[0].ready,false);assert.equal(abilityStates(w)[0].progress,0);run(w,Math.floor((h.reloadTime-.1)*60),true);assert.equal(w.shots,shots);assert.equal(w.player.ammo,0);assert.ok(w.player.reloading>0);assert.ok(abilityStates(w)[0].progress>.8);run(w,7);assert.equal(w.player.ammo,h.magazine);assert.equal(w.player.reloading,0);assert.equal(w.events.filter(e=>e.type==='reloadEnd').length,1);run(w,300);assert.equal(w.events.filter(e=>e.type==='reloadStart').length,1);});
test('an idle partial magazine stays partial with no fake reload event',()=>{const w=world('zelensky');w.step(1/60,{...IDLE,fire:true});run(w,600);assert.equal(w.player.ammo,7);assert.equal(w.events.filter(e=>e.type.startsWith('reload')).length,0);});
test('sniper needs a new press, bolt cycling and a long reload; holding never spams',()=>{const w=world('bilozerska');run(w,600,true);assert.equal(w.shots,1);assert.equal(w.player.ammo,2);run(w,1);w.step(1/60,{...IDLE,fire:true});assert.equal(w.shots,2);run(w,1);w.step(1/60,{...IDLE,fire:true});assert.equal(w.shots,2,'cannot bypass bolt by tapping');run(w,100);w.step(1/60,{...IDLE,fire:true});assert.equal(w.shots,3);assert.equal(w.player.reloading,4.8);run(w,400,true);assert.equal(w.shots,3,'holding through reload does not fire');run(w,1);w.step(1/60,{...IDLE,fire:true});assert.equal(w.shots,4);});
for(const id of ['bandera','ghost','bayraktar']as const)test(id+' fires bounded bursts with mandatory gaps',()=>{const w=world(id),times:number[]=[];let before=0;for(let i=0;i<240;i++){w.step(1/60,{...IDLE,fire:true});if(w.shots>before){times.push(w.time);before=w.shots;}if(times.length===w.hero.burst+1)break;}assert.equal(times.length,w.hero.burst+1);assert.ok(times[w.hero.burst]-times[w.hero.burst-1]>=w.hero.burstPause-.001);assert.ok(times[1]-times[0]<w.hero.burstPause);const tap=world(id);tap.step(1/60,{...IDLE,fire:true});tap.step(1/60,IDLE);for(let i=0;i<10;i++)tap.step(1/60,{...IDLE,fire:i%2===0});assert.equal(tap.shots,1,'tap cannot cancel the burst gap');});
test('ordinary sniper round hits one body only and cannot pierce walls; ultimate remains piercing',()=>{const w=world('bilozerska'),first=target(w,8),second=target(w,10);w.step(1/60,{...IDLE,fire:true});run(w,30);assert.equal(first.hp,918);assert.equal(second.hp,1000);assert.equal(w.hits,1);w.step(1/60,{...IDLE,ultimate:true});run(w,40);assert.equal(first.hp,418);assert.equal(second.hp,500);
 const cover=world('bilozerska'),foe=target(cover,10);cover.boxes.push({id:cover.nextId(),x:8,y:0,w:.2,h:2,hp:50,maxHp:50,kind:'wall'});cover.step(1/60,{...IDLE,fire:true});run(cover,20);assert.equal(foe.hp,1000,'destroyed wall still consumes this round');});
for(const h of HEROES)test(h.id+' shot has a hard range cap even on the last simulation step',()=>{const w=world(h.id);w.boxes=[];w.step(1/60,{...IDLE,fire:true});const b=w.bullets[0],origin=5+.45;assert.ok(b,h.id);for(let i=0;i<120&&b.life>0;i++)w.step(1/30,IDLE);assert.ok(Math.abs(b.x-origin)<=h.range+1e-8,`${h.id}: ${b.x-origin} > ${h.range}`);});
test('reload freezes on pause, permits movement and skills, and resets on rescue and respawn',()=>{const w=world('bilozerska');empty(w);w.mode='paused';const state=JSON.stringify(w.player);run(w,500,true);assert.equal(JSON.stringify(w.player),state);w.mode='playing';const x=w.player.x;w.step(1/60,{...IDLE,move:1,jump:true,special:true,ultimate:true});assert.ok(w.player.x>x);assert.ok(w.player.vy>0);assert.ok(w.effects.some(e=>e.kind==='special'));assert.ok(w.effects.some(e=>e.kind==='ultimate'));assert.equal(w.player.ammo,0);w.player.invulnerable=0;w.damagePlayer(100);assert.equal(w.player.ammo,3);assert.equal(w.player.reloading,0);emptyAgain(w);w.player.x=w.allies[0].x;w.player.y=0;w.step(1/60,{...IDLE,interact:true});assert.equal(w.heroId,'it-army');assert.equal(w.player.ammo,4);assert.equal(w.player.reloading,0);});
function emptyAgain(w:World){for(let i=0;i<4000&&!w.player.reloading;i++)w.step(1/60,{...IDLE,fire:!w.player.weaponTrigger});assert.ok(w.player.reloading>0);}
test('Mamai can use his saber during pistol reload without refilling or spending another shot',()=>{const w=world('mamai');w.step(1/60,{...IDLE,fire:true});run(w,40);const e=target(w,7);w.step(1/60,{...IDLE,fire:true});assert.equal(e.hp,922);assert.equal(w.player.ammo,0);assert.ok(w.player.reloading>2);assert.equal(w.events.filter(e=>e.type==='reloadStart').length,1);});
test('a held gamepad trigger observes the same finite magazine and burst gaps',()=>{const w=world('ghost');const pad={id:'Test',index:0,mapping:'standard',connected:true,axes:[0,0],buttons:Array.from({length:18},(_,i)=>({pressed:i===7,value:i===7?1:0}))};for(let i=0;i<240&&!w.player.reloading;i++)w.step(1/60,padActions(pad,freshBindings()));assert.equal(w.shots,15);assert.equal(w.player.ammo,0);run(w,90,true);assert.equal(w.shots,15);});
